### ISSUE TITLE
[IOS] @expo/xcpretty is crashing near the end of my local EAS build

### ISSUE THREAD

**Issue by tylerc** [expo/eas-cli#1011]
### Summary

I'm doing an EAS build locally with this command: `EXPO_LOCAL_BUILD_SKIP_CLEANUP=1 eas build -p ios --local --non-interactive`

Near the end of the build (I believe during the archive step, or just before) I get the following exception:

```
/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/Formatter.js:664
    return Array(width).join(' ');
           ^

RangeError: Invalid array length
    at fill (/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/Formatter.js:664:12)
    at formatWarningOrError (/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/Formatter.js:638:67)
    at ExpoRunFormatter.formatCompileWarning (/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/Formatter.js:466:29)
    at MetroParser.formatCompileWarning (/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/Parser.js:473:31)
    at MetroParser.parse (/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/Parser.js:23:25)
    at MetroParser.parse (/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/MetroParser.js:18:22)
    at /Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/Formatter.js:121:41
    at Array.forEach (<anonymous>)
    at ExpoRunFormatter.pipe (/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/xcpretty/build/Formatter.js:120:28)
    at Socket.<anonymous> (/Users/tylerchurch/.npm/_npx/1653/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/xcpretty.js:55:41)
    Error: npx exited with non-zero code: 1
```

In theory this might happen for non-local builds as well, but I'm also facing signing issues with EAS build, so I can't confirm.

### Managed or bare?

managed (but with some native extensions thanks to mods and EAS build)

### Environment

```
$ npx expo-env-info 
npx: installed 1 in 0.968s

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
      Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/tylerchurch/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 2 Bumblebee 2021.1.1 Patch 2
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.3.0
    Expo Workflow: bare
```

### Error output

See above.

### Reproducible demo or steps to reproduce from a blank project

Unfortunately, I've been debugging our iOS EAS builds all day and this is just the latest in many errors, so I don't have a reproducible demo for you yet, as I'm exhausted.

However, I have a good idea on a fix for this particular problem.

Following the stack trace, if you open up the sources to the `@expo/xcpretty` npm package, you'll find the following two functions:

```js
function parseOptionalInt(text) {
    if (!text)
        return undefined;
    try {
        return parseInt(text, 10);
    }
    catch {
        return undefined;
    }
}

function fill(width) {
    return Array(width).join(' ');
}
```

The result of `parseOptionalInt()` is eventually fed into `fill()`. The following REPL session should make the error in logic obvious:

```sh
> parseOptionalInt('foo')
NaN
> parseOptionalInt('-1')
-1
> fill(NaN)
Uncaught RangeError: Invalid array length
    at fill (REPL19:2:12)
> fill(-1)
Uncaught RangeError: Invalid array length
    at fill (REPL19:2:12)
```

As far as I'm aware, `parseInt` in JavaScript never throws, it only returns NaN on failure, thus the implementation of `parseOptionalInt` is misguided.

I propose something like this:

```js
function parseOptionalInt(text) {
    if (!text)
        return undefined;
    const result = parseInt(text, 10);
    return isNaN(result) ? undefined : result;
}

function fill(width) {
    if (width > 0) {
        return Array(width).join(' ');
    }
    return '';
}
```

If `@expo/xcpretty` was a public repo, I would've sent this as a pull request, but alas, it doesn't appear to exist anywhere except on npm.

Until this is fixed, my local EAS build will contain manual steps.

**Comment by wkozyra95** [comment]
Thanks for the detailed issue, I'll message here when the change will be deployed

**Comment by tylerc** [comment]
@wkozyra95 Excellent! Thank you!

**Comment by tylerc** [comment]
@wkozyra95 looks like my local build is working now, thank you so much!

Now to see if I can get a non-local build working...
