### ISSUE TITLE
Project with specific name (non-ASCII followed by numbers) fails to build

### ISSUE THREAD

**Issue by IlyaSemenov** [expo/eas-cli#1035]
### Build/Submit details page URL

https://expo.dev/accounts/123nsk/projects/eg11-app/builds/e9bc3ec0-51c9-4eef-8fd6-ccb6be42d0df

### Summary

If project name (`expo.name` in `app.json`) is non-ASCII characters followed by digits (for example: `ЕГ11` or `Ю7`), it fails to build. This is not happening when there are no digits in name.

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nodenv/versions/16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nodenv/versions/16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nodenv/versions/16.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.48.2
    Expo Workflow: managed

### Error output

```
...
[PREPARE_CREDENTIALS] Preparing credentials for target '7'
...
[CONFIGURE_XCODE_PROJECT] Configuring Xcode project
[CONFIGURE_XCODE_PROJECT] Assigning provisioning profile '*[expo] com.123nsk.eg11app AppStore 2022-03-26T07:16:38.347Z' (Apple Team ID: 5ZEMT2V52M) to target '7'
[CONFIGURE_XCODE_PROJECT]
Error: Could not find target '7' in project.pbxproj
    at findNativeTargetByName (/Users/semenov/.npm/_npx/b792985cb050f437/node_modules/@expo/config-plugins/build/ios/Target.js:137:11)
    at Object.setProvisioningProfileForPbxproj (/Users/semenov/.npm/_npx/b792985cb050f437/node_modules/@expo/config-plugins/build/ios/ProvisioningProfile.js:47:79)
    at configureXcodeProject (/Users/semenov/.npm/_npx/b792985cb050f437/node_modules/@expo/build-tools/dist/ios/configure.js:11:56)
    at /Users/semenov/.npm/_npx/b792985cb050f437/node_modules/@expo/build-tools/dist/builders/ios.js:48:61
    at BuildContext.runBuildPhase (/Users/semenov/.npm/_npx/b792985cb050f437/node_modules/@expo/build-tools/dist/context.js:48:34)
    at Object.iosBuilder (/Users/semenov/.npm/_npx/b792985cb050f437/node_modules/@expo/build-tools/dist/builders/ios.js:47:23)
    at async buildIosAsync (/Users/semenov/.npm/_npx/b792985cb050f437/node_modules/eas-cli-local-build-plugin/dist/ios.js:49:27)
    at async buildAsync (/Users/semenov/.npm/_npx/b792985cb050f437/node_modules/eas-cli-local-build-plugin/dist/build.js:28:32)
    at async main (/Users/semenov/.npm/_npx/b792985cb050f437/node_modules/eas-cli-local-build-plugin/dist/main.js:16:9)
```

### Reproducible demo or steps to reproduce from a blank project

Edit `app.json` and set `name` to `Ю7`:

```json
{
  "expo": {
    "name": "Ю7",
  }
}
```

Run:

```
eas build --platform ios --local
```

It doesn't matter what you choose for logging into Apple account and/or enabling push notifications. The app will fail to build.

**Comment by wkozyra95** [comment]
Unfortunately, this known issue with `expo prebuild`, changing that behavior is problematic without breaking other apps. As a workaround, you can use ascii name here and override it via locales. https://docs.expo.dev/distribution/app-stores/#localizing-your-ios-app
