### ISSUE TITLE
Setting EAS_LOCAL_BUILD_WORKINGDIR for local build not working

### ISSUE THREAD

**Issue by bombillazo** [expo/eas-cli#1155]
### Summary

When running a local EAS build and setting the `EAS_LOCAL_BUILD_WORKINGDIR` options, the process fails.

### Managed or bare?

managed

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: * => 0.3.17 
      expo: * => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.1
      expo-cli: 5.4.9
    Expo Workflow: bare

### Error output

```sh
$ EAS_LOCAL_BUILD_SKIP_CLEANUP=1 EAS_LOCAL_BUILD_WORKINGDIR=../../tmp eas build -p android --profile development --local
✔ Linked to project @org/project (​https://expo.dev/accounts/org/projects/project​)
Specifying "android.package" in app.config.js is deprecated for bare workflow projects.
EAS Build depends only on the value in the native code. Please remove the deprecated configuration.
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials _zPmLAbw9S (default)
ANDROID_NDK_HOME environment variable was not specified, continuing build without NDK
[SETUP_WORKINGDIR] Preparing workingdir ../../tmp
[START_BUILD] Starting build
  "job": {
    "type": "generic",
    "platform": "android",
    "projectRootDirectory": "apps/mobile",
    "projectArchive": {
      "type": "PATH",
      "path": "/var/folders/kp/brk5wgsn5mz73fxhj06c9tdw0000gn/T/eas-cli-nodejs/1bc012c4-6ccc-4d3b-b4ef-1657d7fac81c.tar.gz"
    },
    "builderEnvironment": {
      "node": "16.14.2",
      "env": {
        "APP_ENV": "dev"
      }
    },
    "cache": {
      "disabled": false,
      "customPaths": [],
      "cacheDefaultPaths": true,
      "clear": false
    },
    "updates": {},
    "developmentClient": true,
    "buildType": "apk",
    "username": "bombillazo",
    "experimental": {}
  }
[PREPARE_PROJECT] tar: could not chdir to '../../tmp/build'
[PREPARE_PROJECT] 
Error: tar exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/@expo/spawn-async/build/spawnAsync.js:43:23)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)
    ...
    at spawnAsync (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at spawn (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/@expo/turtle-spawn/dist/index.js:17:47)
    at downloadAndUnpackProject (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/@expo/build-tools/dist/utils/project.js:83:38)
    at async /Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/@expo/build-tools/dist/utils/project.js:19:9
    at async BuildContext.runBuildPhase (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/@expo/build-tools/dist/context.js:49:28)
    at async setup (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/@expo/build-tools/dist/utils/project.js:18:5)
    at async Object.androidBuilder (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/@expo/build-tools/dist/builders/android.js:14:5)
    at async buildAndroidAsync (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/eas-cli-local-build-plugin/dist/android.js:49:27)
    at async buildAsync (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/eas-cli-local-build-plugin/dist/build.js:24:32)
    at async main (/Users/user/.npm/_npx/b36b56d605c88fbd/node_modules/eas-cli-local-build-plugin/dist/main.js:16:9)

Build failed
Skipping cleanup, ../../tmp won't be removed.
tar exited with non-zero code: 1
```

### Reproducible demo or steps to reproduce from a blank project

1. Setup Expo project for building
2. Run the command
```
EAS_LOCAL_BUILD_SKIP_CLEANUP=1 EAS_LOCAL_BUILD_WORKINGDIR=../../tmp eas build -p android --local
```

**Comment by wkozyra95** [comment]
use absolute paths, also those envs are more intended for development, if you want to debug your build use `eas build:inspect`
