### ISSUE TITLE
EAS Build Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by Alcamech** [expo/eas-cli#1182]
### Build/Submit details page URL

https://expo.dev/accounts/euterpesolutions/projects/quantify-mobile/builds/9b13e024-5e69-44be-8264-c7bc46380045

### Summary

When running a eas build for Android my organization receives the following error

```
Running './gradlew :app:bundleRelease' in /home/expo/workingdir/build/frontend/android

[stderr] Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

### Managed or bare?

Managed

### Environment

```
expo-env-info 1.0.4 environment info:
    System:
      OS: Linux 5.18 Fedora Linux 36 (Workstation Edition)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 14.19.0 - /usr/bin/node
      npm: 6.14.16 - /usr/bin/npm
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.9
    Expo Workflow: bare
```

### Error output

```
✔ Select platform › Android
Error: Cannot find module 'expo-dev-client/package.json'
Require stack:
- /home/lawton/Development/quantify-mobile/frontend/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at resolveFileName (/usr/local/lib/node_modules/eas-cli/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/usr/local/lib/node_modules/eas-cli/node_modules/resolve-from/index.js:43:9)
    at module.exports (/usr/local/lib/node_modules/eas-cli/node_modules/resolve-from/index.js:46:47)
    at isExpoDevClientInstalledAsync (/usr/local/lib/node_modules/eas-cli/build/build/utils/devClient.js:68:36)
    at ensureExpoDevClientInstalledForDevClientBuildsAsync (/usr/local/lib/node_modules/eas-cli/build/build/utils/devClient.js:18:15)
    at runBuildAndSubmitAsync (/usr/local/lib/node_modules/eas-cli/build/build/runBuildAndSubmit.js:47:79)
    at async Build.runAsync (/usr/local/lib/node_modules/eas-cli/build/commands/build/index.js:20:9)
    at async Build._run (/usr/local/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:67:22)
    at async Config.runCommand (/usr/local/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js:268:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/lawton/Development/quantify-mobile/frontend/noop.js' ]
}
- Linking to project @euterpesolutions/quantify-mobile
✔ Linked to project @euterpesolutions/quantify-mobile (https://expo.dev/accounts/euterpesolutions/projects/quantify-mobile)
Specifying "android.package" in app.json is deprecated for bare workflow projects.
EAS Build depends only on the value in the native code. Please remove the deprecated configuration.
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials vPVCS6IbKG (default)

Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
- Compressing project files
- Uploading to EAS Build (0 / 507 KB)
✔ Uploaded to EAS 
Starting Android build

Build details: https://expo.dev/accounts/euterpesolutions/projects/quantify-mobile/builds/594a35a8-bd90-4e4d-a6dd-180ba46ef4e4

Waiting for build to complete. You can press Ctrl+C to exit.
- Waiting for build to complete.
✖ Build failed

🤖 Android build failed:
Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

### Reproducible demo or steps to reproduce from a blank project

`eas build`

**Comment by wkozyra95** [comment]
> When running a eas build for Android my organization receives the following error

that error means that your gradle wrapper is missing from your repo, most likely it's gitignored

> Managed or bare?
Managed

but expo-env-info output below is detecting it as a bare project, so you ejected at some point, either delete android and ios directories or add them to the gitignore

> Reproducible demo or steps to reproduce from a blank project
`eas build`

If you don't know a how to reproduce the issue just say that, providing false information about the issue wastes everyone's time even in cases like this where it's obvious that you did not run those reproduction steps on a blank project
