### ISSUE TITLE
EAS build --local  takes 30+ mins.

### ISSUE THREAD

**Issue by fantasyado** [expo/eas-cli#1189]
### Build/Submit details page URL

it's local build

### Summary

EAS build --local  takes 30+ mins.  Looking into the build log task **bundleReleaseJsAndAssets** cost around 12 mins.
Related log:  

**13:21:24** [RUN_GRADLEW] > Task :app:bundleReleaseJsAndAssets
**13:33:02** [RUN_GRADLEW] Execution optimizations have been disabled for task ':app:bundleReleaseJsAndAssets' to ensure correctness due to the following reasons:
13:33:02 [RUN_GRADLEW]   - Gradle detected a problem with the following location: '/opt/user/dev/eas_workingdir/build/expo-proj'. Reason: Task ':app:bundleReleaseJsAndAssets' uses this output of task ':expo-application:compileReleaseAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

### Managed or bare?

managed

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: Linux 3.10 CentOS Linux 7 (Core)
      Shell: 4.2.46 - /bin/bash
    Binaries:
      Node: 16.14.2 - ~/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/16.14.2/bin/node
      Yarn: 1.22.18 - /opt/nick/node-v17.9.0-linux-x64/bin/yarn
      npm: 8.5.0 - ~/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/16.14.2/bin/npm
    npmPackages:
      expo: ~43.0.5 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

================
Expo doctor log from build log:

13:18:15 [RUN_EXPO_DOCTOR] Running "expo doctor"
13:18:17 [RUN_EXPO_DOCTOR] - Finding all copies of expo-modules-autolinking
13:18:18 [RUN_EXPO_DOCTOR] ��� Failed to find dependency tree for expo-modules-autolinking: npm exited with non-zero code: 1
13:18:18 [RUN_EXPO_DOCTOR] [01:18:18] npm exited with non-zero code: 1
13:18:18 [RUN_EXPO_DOCTOR] [01:18:18] Error: npm exited with non-zero code: 1
13:18:18 [RUN_EXPO_DOCTOR]     at ChildProcess.completionListener (/opt/nick/dev/npm_cache/_npx/2773/lib/node_modules/eas-cli-local-build-plugin/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
13:18:18 [RUN_EXPO_DOCTOR]     at Object.onceWrapper (events.js:520:26)
13:18:18 [RUN_EXPO_DOCTOR]     at ChildProcess.emit (events.js:400:28)
13:18:18 [RUN_EXPO_DOCTOR]     at maybeClose (internal/child_process.js:1058:16)
13:18:18 [RUN_EXPO_DOCTOR]     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
13:18:18 [RUN_EXPO_DOCTOR]     ...
13:18:18 [RUN_EXPO_DOCTOR]     at spawnAsync (/opt/nick/dev/npm_cache/_npx/2773/lib/node_modules/eas-cli-local-build-plugin/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
13:18:18 [RUN_EXPO_DOCTOR]     at explainAsync (/opt/nick/dev/npm_cache/_npx/2773/lib/node_modules/eas-cli-local-build-plugin/node_modules/expo-cli/src/commands/info/doctor/depedencies/explain.ts:24:30)
13:18:18 [RUN_EXPO_DOCTOR]     at warnAboutDeepDependenciesAsync (/opt/nick/dev/npm_cache/_npx/2773/lib/node_modules/eas-cli-local-build-plugin/node_modules/expo-cli/src/commands/info/doctor/depedencies/explain.ts:43:30)
13:18:18 [RUN_EXPO_DOCTOR]     at validateSupportPackagesAsync (/opt/nick/dev/npm_cache/_npx/2773/lib/node_modules/eas-cli-local-build-plugin/node_modules/expo-cli/src/commands/info/doctor/doctorAsync.ts:28:13)
13:18:18 [RUN_EXPO_DOCTOR]     at actionAsync (/opt/nick/dev/npm_cache/_npx/2773/lib/node_modules/eas-cli-local-build-plugin/node_modules/expo-cli/src/commands/info/doctor/doctorAsync.ts:41:5)
13:18:19 [RUN_EXPO_DOCTOR] Command "expo doctor" failed.

### Error output

<img width="378" alt="image" src="https://user-images.githubusercontent.com/10321851/176836745-e566c6ae-2512-4d5b-bbc7-d1445acb6cf2.png">

### Reproducible demo or steps to reproduce from a blank project

not available now. I'll try to create one later.

**Comment by fantasyado** [comment]
Thanks @wkozyra95, We did use FontAwesome in our Proj. I will see if remove it can help with the build time :)
