### ISSUE TITLE
Running `eas update` failed with message (sourcemap related?) with hermes

### ISSUE THREAD

**Issue by deathemperor** [expo/eas-cli#1274]
### Build/Submit details page URL

https://expo.dev/accounts/papaya-insurtech/projects/papaya-care/builds/09e112ee-da42-4d96-8e09-d5c887f3f5d9

### Summary

Running `eas update` failed with message

### Managed or bare?

Bare

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 3.2.1 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/deathemperor/.gem/ruby/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        Android NDK: 20.0.5594570
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.2
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: bare
```

```
🎉 Didn't find any issues with the project!
```

### Error output

```
✔ Linked to project @papaya-insurtech/papaya-care
✔ Which branch would you like to publish on? › main - current update: "configure app.jso for eas update" (5 days ago by tech.admin.papaya)
✔ Please enter an update message. … added all days of code, couldn't keep track of what done
- Building bundle...
[expo-cli] --non-interactive is not supported, use $CI=1 instead
- Building bundle...
[expo-cli] Expo Metro config:
- Building bundle...
[expo-cli] - Version: 0.3.21
- Building bundle...
[expo-cli] - Bundler target: bare
- Building bundle...
[expo-cli] - Legacy: false
- Building bundle...
[expo-cli] - Extensions: ts, tsx, js, jsx, json
- Building bundle...
[expo-cli] - React Native: /Users/deathemperor/papaya/star-gooseberry/node_modules/react-native
- Building bundle...
[expo-cli] - Babel config: /Users/deathemperor/papaya/star-gooseberry/babel.config.js
- Building bundle...
[expo-cli] - Resolver Fields: react-native, browser, main
- Building bundle...
[expo-cli] - Watch Folders:
- Building bundle...
[expo-cli] - Node Module Paths:
- Building bundle...
[expo-cli] - Exotic: false
- Building bundle...
[expo-cli]
- Building bundle...
[expo-cli] Expo Metro config:
- Building bundle...
[expo-cli] - Version: 0.3.21
- Building bundle...
[expo-cli] - Bundler target: bare
- Building bundle...
[expo-cli] - Legacy: false
- Building bundle...
[expo-cli] - Extensions: ts, tsx, js, jsx, json
- Building bundle...
[expo-cli] - React Native: /Users/deathemperor/papaya/star-gooseberry/node_modules/react-native
- Building bundle...
[expo-cli] - Babel config: /Users/deathemperor/papaya/star-gooseberry/babel.config.js
- Building bundle...
[expo-cli] - Resolver Fields: react-native, browser, main
- Building bundle...
[expo-cli] - Watch Folders:
- Building bundle...
[expo-cli] - Node Module Paths:
- Building bundle...
[expo-cli] - Exotic: false
- Building bundle...
[expo-cli] Starting Metro Bundler
- Building bundle...
[expo-cli] Android Bundling complete 9537ms
- Building bundle...
[expo-cli] iOS Bundling complete 9539ms
- Building bundle...
[expo-cli] iOS Building Hermes bytecode for the bundle
- Building bundle...
[expo-cli]
- Building bundle...
[expo-cli] Error: Invalid mapping: {"generated":{"line":1,"column":179},"source":"/Users/deathemperor/papaya/star-gooseberry/node_modules/metro-runtime/src/polyfills/}
- Building bundle...
[expo-cli] Error: Invalid mapping: {"generated":{"line":1,"column":179},"source":"/Users/deathemperor/papaya/star-gooseberry/node_modules/metro-runtime/src/polyfills/}
- Building bundle...
[expo-cli]     at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/deathemperor/papaya/star-gooseberry/node_modules/metro-source-map/node_modules/sour)
- Building bundle...
[expo-cli]     at SourceMapGenerator_addMapping [as addMapping] (/Users/deathemperor/papaya/star-gooseberry/node_modules/metro-source-map/node_modules/source-map/lib/)
- Building bundle...
[expo-cli]     at /Users/deathemperor/papaya/star-gooseberry/node_modules/metro-source-map/src/composeSourceMaps.js:41:15
- Building bundle...
[expo-cli]     at MappingsConsumer.eachMapping (/Users/deathemperor/papaya/star-gooseberry/node_modules/metro-source-map/src/Consumer/AbstractConsumer.js:36:16)
- Building bundle...
[expo-cli]     at composeSourceMaps (/Users/deathemperor/papaya/star-gooseberry/node_modules/metro-source-map/src/composeSourceMaps.js:35:16)
- Building bundle...
[expo-cli]     at createHermesSourcemapAsync (/Users/deathemperor/papaya/star-gooseberry/node_modules/@expo/dev-server/build/HermesBundler.js:69:27)
- Building bundle...
[expo-cli]     at async Promise.all (index 1)
- Building bundle...
[expo-cli]     at async Object.buildHermesBundleAsync (/Users/deathemperor/papaya/star-gooseberry/node_modules/@expo/dev-server/build/HermesBundler.js:51:34)
- Building bundle...
[expo-cli]     at async maybeAddHermesBundleAsync (/Users/deathemperor/papaya/star-gooseberry/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:130:40)
- Building bundle...
[expo-cli]     at async Object.bundleAsync (/Users/deathemperor/papaya/star-gooseberry/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:143:32)
- Building bundle...
✖ Failed to build bundle!
    Error: /Users/deathemperor/papaya/star-gooseberry/node_modules/expo/bin/cli.js exited with non-zero code: 1
```

### Reproducible demo or steps to reproduce from a blank project

I don't have one

**Comment by nandorojo** [comment]
Did you ever fix this @deathemperor? I'm getting the same thing.

**Comment by jonjts** [comment]
@deathemperor did you fix it?
I got the same error here
