### ISSUE TITLE
Apple ID Authentication — Cannot login after Apple ID email change

### ISSUE THREAD

**Issue by supryan** [expo/eas-cli#1294]
### Summary

I recently updated the email address on my Apple ID account and it seems I cannot login to Apple via `eas-cli` or legacy build system. **Email and password is correct, I'm able to login on the web portal**.

- [X] Tried the old email/username as well. 
- [X] All user agreements signed on the portal. 

Get the following output:

```
Accessing credentials for rgordon in project never-better
✔ Do you have access to the Apple account that will be used for submitting this app to the App Store? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … ********@supryan.com
› The password is only used to authenticate with Apple and never stored on EAS servers
  Learn more.
✔ Password (for ********@supryan.com): … ****************************
› Saving Apple ID password to the local Keychain
  Learn more.
✖ Logging in...
Invalid username and password combination. Used '********@supryan.com' as the username.
```

### Managed or bare?

Managed

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 27, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.59 => 0.1.59
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Error output

```
Accessing credentials for rgordon in project never-better
✔ Do you have access to the Apple account that will be used for submitting this app to the App Store? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … ********@supryan.com
› The password is only used to authenticate with Apple and never stored on EAS servers
  Learn more.
✔ Password (for ********@supryan.com): … ****************************
› Saving Apple ID password to the local Keychain
  Learn more.
✖ Logging in...
Invalid username and password combination. Used '********@supryan.com' as the username.
```

### Reproducible demo or steps to reproduce from a blank project

1. Change email address/username for Apple ID
2. Logout of the eas if already logged in
3. `eas login`
4. Run a new build and provide Apple account credentials
5. See error

**Comment by brentvatne** [comment]
try running: `EXPO_APP_STORE_DEBUG=1 npx @expo/apple-utils login` and share the output

**Comment by brentvatne** [comment]
and if that doesn't work.. try `EXPO_NO_KEYCHAIN=1 EXPO_APP_STORE_DEBUG=1 npx @expo/apple-utils login`

**Comment by supryan** [comment]
@brentvatne the latter worked for me! I'm all logged in now thank you for a quick response!

**Comment by simontoulouze** [comment]
> and if that doesn't work.. try `EXPO_NO_KEYCHAIN=1 EXPO_APP_STORE_DEBUG=1 npx @expo/apple-utils login`

I had the following issue when running `eas build -p ios` and the above solution worked like a charm, thanks @brentvatne !!
```
✖ Logging in...
Authentication with Apple Developer Portal failed!
    Error: Apple Service Error -36607. Unable to sign you in to your Apple ID. Try again later. <a
     target="_blank" href="https://support.apple.com/kb/HT212522 ">Learn more.<span
    class="sr-only"> Opens in a new window.</span></a>
node:child_process:935
    throw err;
```

**Comment by clintonimaroo** [comment]
> Get the following output:

I cannot login to Apple via eas-cli or legacy build system. Email and password is correct, I'm able to login on the web portal.

**Get the following output:**

`➜  app-mobile git:(main) ✗ eas device:create
This command lets you register your Apple devices (iPhones, iPads and Macs) for internal distribution of your app.
Internal distribution means that you won't need to upload your app archive to App Store / Testflight.
Your app archive (.ipa) will be installable on your equipment as long as you sign your application with an adhoc provisioning profile.
The provisioning profile needs to contain the UDIDs (unique identifiers) of your iPhones, iPads and Macs.

First of all, choose the Expo account under which you want to register your devices.
Later, authenticate with Apple and choose your desired Apple Team (if your Apple ID has access to multiple teams).

✔ You're inside the project directory. Would you like to use the app-mobile account? … yes
› Log in to your Apple Developer account to continue
✔ Apple ID: … ********@hotmail.com
› Using password for ***********@hotmail.com from your local Keychain
  Learn more
✖ Logging in...
Invalid username and password combination. Used '**********@hotmail.com' as the username.
› Removed Apple ID password from the native Keychain
? Would you like to try again? › no / yes`


I've tried this commands already, but still not working. https://github.com/expo/eas-cli/issues/1294#issuecomment-1222609571

https://github.com/expo/eas-cli/issues/1294#issuecomment-1222610936

**Comment by PrennerProducts** [comment]
i have the same problem, but the solution above is not woking:

FF416:FDTest user252449$ EXPO_NO_KEYCHAIN=1 EXPO_APP_STORE_DEBUG=1 npx @expo/apple-utils login
-- Enabled debug logging --
Log in to your Apple Developer account to continue
✔ Apple ID: … prenner.products@gmail.com
› The password is only used to authenticate with Apple and never stored on Expo servers
Learn more: https://bit.ly/2VtGWhU
✔ Password (for prenner.products@gmail.com): … **********
Skip storing Apple ID password in the local Keychain.
⠋ Logging in...GET https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42
⠧ Logging in...200  (GET https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42)
POST https://idmsa.apple.com/appleauth/auth/signin
⠙ Logging in...Error: Request failed with status code 409 (POST https://idmsa.apple.com/appleauth/auth/signin)
✔ Logged in, verify your Apple account to continue
GET https://idmsa.apple.com/appleauth/auth
Error: Request failed with status code 423 (GET https://idmsa.apple.com/appleauth/auth)
✖ Logging in...
This phone number cannot be used at this time. Try again later or choose a different number.
Error: This phone number cannot be used at this time. Try again later or choose a different number.
    at a (/Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:718209)
    at o (/Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:718164)
    at t.idmsaRequestAsync (/Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:718423)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.requestAuthAsync (/Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:731967)
    at async t.handleTwoFactorAuthentication (/Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:728132)
    at async S (/Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:709726)
    at async t.loginAsync (/Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:713310)
    at async /Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:968934
    at async c.<anonymous> (/Users/user252449/.npm/_npx/0c9fefa1aae6e81c/node_modules/@expo/apple-utils/build/index.js:1:973474)
FF416:FDTest user252449$

**Comment by WillSmithTE** [comment]
uninstalling and reinstalling `eas` globally did it for me 🤷‍♂️

**Comment by iAhtasham** [comment]
I am still facing this very same issue, uninstalling and reinstalling eas globally didnt work.

**Comment by clintonimaroo** [comment]
I just had to update my Expo CLI, then the problem was fixed.

**Comment by SirCameron** [comment]
I had installed the cli as a dependency by mistake at some point. That was overriding the globally installed version. 
So I removed that, updated global and all worked :)

**Comment by amayan167** [comment]
Try putting in your Apple ID password, which for me was different than my Apple Developer ID Password. Waisted a day with it telling me to put in the wrong password.

**Comment by douglowder** [comment]
Fixed by updating the Expo CLI.
