### ISSUE TITLE
eas build -p ios --profile development --local , error Distribution certificate with fingerprint xxxxxxxxxxx hasn't been imported successfully

### ISSUE THREAD

**Issue by PROMEDIK-INDONESIA** [expo/eas-cli#1331]
### Build/Submit details page URL

https://expo.dev/accounts/dirabbieto/projects/iidi-project/builds/0fbe0224-2b74-420c-99f5-2ff56e8b8d47

### Summary

i want to install React Native Google Mobile Ads (https://github.com/invertase/react-native-google-mobile-ads) on my project, but when i finished setup and run `eas build -p ios --profile development --local` on my terminal, it shows error `Error: Distribution certificate with fingerprint *************** hasn't been imported successfully`.

### Managed or bare?

managed

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
      Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    Expo Workflow: managed
```

```
expo doctor
✖ Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/prebuild-config failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @unimodules/core failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @unimodules/react-native-adapter failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for react-native-unimodules failed. This validation is only available on Node 16+ / npm 8.
🎉 Didn't find any issues with the project!
```

### Error output

```
[RUN_EXPO_DOCTOR] Running "expo doctor"
[RUN_EXPO_DOCTOR] - Finding all copies of expo-modules-autolinking
[RUN_EXPO_DOCTOR] ✖ Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
[RUN_EXPO_DOCTOR] [10:36:18] No dependencies found for expo-modules-autolinking
[RUN_EXPO_DOCTOR] - Finding all copies of @expo/config-plugins
[RUN_EXPO_DOCTOR] ✖ Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
[RUN_EXPO_DOCTOR] [10:36:18] No dependencies found for @expo/config-plugins
[RUN_EXPO_DOCTOR] - Finding all copies of @expo/prebuild-config
[RUN_EXPO_DOCTOR] ✖ Dependency tree validation for @expo/prebuild-config failed. This validation is only available on Node 16+ / npm 8.
[RUN_EXPO_DOCTOR] [10:36:19] No dependencies found for @expo/prebuild-config
[RUN_EXPO_DOCTOR] 
[RUN_EXPO_DOCTOR] [10:36:25] 🎉 Didn't find any issues with the project!
[PREPARE_CREDENTIALS] Preparing credentials
[PREPARE_CREDENTIALS] Creating keychain
[PREPARE_CREDENTIALS] Preparing credentials for target 'iidiproject'
[PREPARE_CREDENTIALS] Getting distribution certificate fingerprint
[PREPARE_CREDENTIALS] Writing distribution certificate to /var/folders/pp/5mmg-d4fn7m22bs86gd5z80000gq/T/b1c6bd60-21a7-4041-8d51-d715692d2b9c.p12
[PREPARE_CREDENTIALS] Importing distribution certificate into the keychain
[PREPARE_CREDENTIALS] Initializing provisioning profile
[PREPARE_CREDENTIALS] Validating whether distribution certificate has been imported successfully
[PREPARE_CREDENTIALS] Destroying keychain - /var/folders/pp/5mmg-d4fn7m22bs86gd5z80000gq/T/turtle-v2-53cb8ca3-f7d2-4186-a808-04fb6ef67a6e.keychain
[PREPARE_CREDENTIALS] 
Error: Distribution certificate with fingerprint xxxxxxxxx hasn't been imported successfully
    at Keychain.ensureCertificateImported (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/credentials/keychain.js:54:19)
    at async IosCredentialsManager.prepareTargetCredentials (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/credentials/manager.js:100:13)
    at async IosCredentialsManager.prepare (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/credentials/manager.js:58:41)
    at async /Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/ios.js:54:20
    at async BuildContext.runBuildPhase (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/context.js:50:28)
    at async buildAsync (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/ios.js:53:29)
    at async Object.iosBuilder (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/ios.js:24:33)
    at async buildIosAsync (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/dist/ios.js:54:12)
    at async buildAsync (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/dist/build.js:42:32)
    at async main (/Users/dira/.npm/_npx/26667/lib/node_modules/eas-cli-local-build-plugin/dist/main.js:16:9)

Build failed
Distribution certificate with fingerprint xxxxxxxxxxx hasn't been imported successfully
    Error: npx exited with non-zero code: 1
- Compressing project files
```

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@dirabbieto/expo-google-admob-setup

**Comment by dsokal** [comment]
Are you getting this error repeatedly? When running `eas build --local` do you see any popup asking to unblock the keychain?

**Comment by PROMEDIK-INDONESIA** [comment]
> Are you getting this error repeatedly? When running `eas build --local` do you see any popup asking to unblock the keychain?

when i tried to running `eas build --local`, it still gives the same error and there is no popup appear.

**Comment by dsokal** [comment]
Do you use `credentials.json`?

**Comment by PROMEDIK-INDONESIA** [comment]
> Do you use `credentials.json`?

no, i don't. should i add it to my root project?

**Comment by PROMEDIK-INDONESIA** [comment]
> 



> No, you don't if you don't need local credentials. I'm just trying to understand the problem. If I understand correctly, you can build the project without `--local` flag without any problems?

yes, it works without any problems.

**Comment by dsokal** [comment]
It seems stupid but can you try restarting your Mac and running local build again?

**Comment by PROMEDIK-INDONESIA** [comment]
> It seems stupid but can you try restarting your Mac and running local build again?

yes, already did that, but still it gives the same error. The error says `Distribution certificate with fingerprint xxxx hasn't been imported successfully`, is there any chance to import distribution certificate manually?

**Comment by mrevanschan** [comment]
same issue for me... build is working on eas server but not on --local. Already tried factory reseting my m1 and following steps from [here]( https://www.youtube.com/watch?v=id0Im72UN6w&t=50s) with fresh project...

**Comment by KiwiKilian** [comment]
I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the donwload) it shows the Certificate is untrusted. Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. No the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.

I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

**Comment by PROMEDIK-INDONESIA** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

hi kiwi, thank you so much for this, your explanation solved my problem.

also thank you @dsokal for helping me!

**Comment by rokasta12** [comment]
@ KiwiKilian
Just wanted to say thanks 🚀

**Comment by NameNull** [comment]
成功了。。。微信：yjavacn

**Comment by NameNull** [comment]
https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer

**Comment by garyThrels** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

Same issue happened again with latest Xcode 14.2 and this certificate solved it

**Comment by johnslemmer** [comment]
I was running in to this issue and fixed it by opening xcode and logging in to my apple developer account inside xcode.  Hope that helps.

**Comment by micksar** [comment]
Thanks a lot @KiwiKilian .
You solved my problem

**Comment by arnabdotpy** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

Thanks a lot man. This worked

**Comment by iamemiliano** [comment]
I usually run "eas build --profile production --platform ios" on Windows and since yesterday I get the following error: 
`Preparing credentials
Creating keychain
Preparing credentials for target 'XXXX'
Getting distribution certificate fingerprint and common name
Fingerprint = "XXXXXXXXXXXXXXXXXXXXXXXX", common name = XXXXXX
Writing distribution certificate to /var/folders/dz/XXXXXXX
Importing distribution certificate into the keychain
Initializing provisioning profile
Validating whether distribution certificate has been imported successfully
Destroying keychain - /var/folders/dz/XXXXXXX/T/turtle-v2-XXXXXXX
Distribution certificate with fingerprint XXXXXX hasn't been imported successfully`

Do you have any ideas?

**Comment by KiwiKilian** [comment]
@iamemiliano This issue is only about using `--local` regarding iOS. Therefore your problem on windows is totally different.

**Comment by TarifEzaz** [comment]
@KiwiKilian's solution works with additional step mentioned here: https://discussions.apple.com/thread/2737481?sortBy=best

**Comment by maniteja-emmadi** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

Thank you so much for this.

**Comment by maison-shibumi** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

this is still very relevant in 2024 - thanks!!

**Comment by kweenyl-frog** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
>
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a --local iOS build successfully downloads the distribution certificate and gets added to the keychain.
>
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

thank you very much! this solved my issue!

**Comment by SamJbori** [comment]
> hy this certificate is missi

Just wanted to say thanks!

**Comment by AlbertCardo** [comment]
I fixed the error by downloading the certificate file https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer and then installing it with [this command I found in StackOverflow](https://stackoverflow.com/a/67334871/4034572):

```shell
security add-trusted-cert -d -r unspecified -k ~/Library/Keychains/login.keychain-db ~/Downloads/AppleWWDRCAG3.cer
```

**Comment by oottoohh** [comment]
am i need regenerate provisioning profile after install Apple Worldwide Developer Relations Certification Authority ? @PROMEDIK-INDONESIA @KiwiKilian

**Comment by nightness** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

Thanks. Wish I found this three hours ago! 😁

**Comment by hasankemaldemirci** [comment]
Cheers ✨ @KiwiKilian

**Comment by bromeooo** [comment]
This works locally for me. I'm running --local builds in github actions and getting 

`Distribution Certificate is not validated for non-interactive builds.`

which i believe is related. Is there a fix for this issue when fetching certs --non-interactive --local in gha? Locally the fix in the comment above did work.

**Comment by cryptobench** [comment]
@bromeooo Did you find a solution to this?

**Comment by bromeooo** [comment]
@cryptobench yes. This error is misleading, it just means expo can't find ANY certs. Try generating certs with the cli and making sure your build is pointed at the right expo project (with the certs).

**Comment by cryptobench** [comment]
@bromeooo Does that mean you upload your cert to the github repo? I am finding it hard to find any documentation that points me towards logging into apple somehow via the github actions runner.

**Comment by bromeooo** [comment]
@cryptobench so expo will set you up. If you use expo - cli locally and run a build with eas. It will prompt you to log in and generate certs for you. The certs are linked to your apple account and will exist on your project expo dashboard. After you do this locally you can run that same build on gh actions and it will find the certs non-interactive

**Comment by giorgosph** [comment]
Hello.

I have the same problem with my certificates. My EAS builds were working as expected until I have created a new App ID and certificates. The problem is that I do not have a Mac so I am using OpenSSL to handle the certificates. 

### Steps Taken
1. I have created the new App ID
2. I have created a keypair locally using OpenSSL and used the private.key to sign a .cer certificate
3. I have created a new distribution certificate from my Apple Developer account using the .cer created above
4. I used OpenSSL to issue a .p12 certificate using the private key and the distribution certificate

Note that I have also issued a certificate for APN.

After those changes the build fails at the "Prepare Credentials" step with error message:

*Distribution certificate with fingerprint xxxxxxxxxxxxxxxxxx hasn't been imported successfully*

**Comment by AugSync** [comment]
> Estaba experimentando el mismo problema. Mientras intentaba depurar, descargué manualmente el Certificado de distribución de la sección Credenciales en el panel de EAS. Al agregarlo a mi llavero de macOS (la contraseña se proporciona en el archivo .md en la descarga), muestra que el Certificado no es confiable.
> 
> Después de seguir este [hilo,](https://developer.apple.com/forums/thread/662300) me faltaba [este](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) certificado más reciente de "Autoridad de certificación de relaciones con desarrolladores de Apple a nivel mundial". Después de agregar este certificado de Apple, el certificado de distribución también es confiable. Además, al eliminar nuevamente el certificado de distribución y luego ejecutar una `--local`compilación de iOS, se descarga correctamente el certificado de distribución y se agrega a la cadena de llaves.
> 
> No estoy seguro de por qué falta este certificado, ya que Apple indica que [debería haberse actualizado con XCode](https://developer.apple.com/support/expiration/) .

Thanks, it works!!!

**Comment by melyux** [comment]
Above workaround doesn't work for me, it says `SecCertificateAddToKeychain: The specified keychain could not be found.`.

**Comment by brunojs02** [comment]
Hello guys i'm getting this error as well, but in my case i don't have a mac so i follow this steps in my linux distro fedora

- created a sign request (.csr) with openssl `openssl req -nodes -newkey rsa:2048 -keyout private_key.key -out cer_sign_request.csr`
- created a certificate in https://developer.apple.com/account/resources/certificates/list and dowloaded it
- transformed `downloaded_certificate.cer` in `certificate.pem` with `openssl x509 -in downloaded_certificate.cer -inform DER -out certificate.pem -outform PEM`
- downloaded and transformed `AppleWWDRCAG3.cer` in `AppleWWDRCAG3.pem` with the command `openssl x509 -in AppleWWDRCAG3.cer -inform DER -out AppleWWDRCAG3.pem -outform PEM`
- and finally export as `certficate.p12` with command `openssl pkcs12 -export -out certificate.p12 -inkey private_key.key -in certificate.pem -certfile AppleWWDRCAG3.pem`

If someone already made this work, tell me the steps i should follow please

**Comment by mffonseca** [comment]
@KiwiKilian @AlbertCardo . Thanks for this! Worked for me.

**Comment by refernando** [comment]
Hello @brunojs02 I also don't have a Mac, so i did the following commands in Windows and it solved the problem:

Generate CSR

```openssl genrsa -out key.key 2048```

```openssl req -new -key key.key -out csr.csr -subj "/CN=Name/OU=Departament/O=Organization/L=City/ST=State/C=CountryCode"```

You should use OpenSSL 1.x to generate a compatible .p12 with Apple. You can install the OpenSSL 3.x for Windows and use the `-legacy` flag in the last command below, to use the 1.x version. If you don't use this flag, it will cause the "Distribution certificate with fingerprint hasn't been imported successfully" error. I have found this solution in this [gist](https://gist.github.com/boodle/77436b2d9facb8e938ad).

```openssl x509 -in <name_of_downloaded_certificate>.cer -inform DER -out certificate.pem -outform PEM```

```openssl pkcs12 -export -inkey mykey.key -in certificate.pem -out certificate.p12 -legacy```

After that, type a password for your p12 file, and done!

**Comment by ArwedSchmidt** [comment]
I was having this as well. Doing a manual build in xcode directly prompted me:
a) to choose a development team (required apple login) and
b) eventually an authorization dialog for keychain access where I could chose to always grant the permission. 

That fixed it in my zsh

**Comment by ArwedSchmidt** [comment]
It happened again to me when migrating to a new Mac. I've fiddled a bit with creating new profiles but that wouldn't work until I ultimately logged into expo.dev and deleted all iOS distribution certificates manually there (and on Apples sites), then recreating one worked without any such issues

**Comment by itrcz** [comment]
You should download p12 from expo and install on local machine to fix an issue

**Comment by StevenJBorik** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

still works in 2025

**Comment by WinnieS0728** [comment]
facing to same issue.
but solve this with another way.

## credential expired

https://docs.expo.dev/app-signing/app-credentials/#provisioning-profiles

find in Expo dashboard > Android & iOS credentials

my credential is expired.

<img width="1316" height="309" alt="Image" src="https://github.com/user-attachments/assets/080a7c91-0154-4824-8b84-ff2be68525e7" />

## solve way

and we solve this by
1. run `eas credentials`
2. choose profile (I use production)
3. login
4. after show this list

<img width="709" height="119" alt="Image" src="https://github.com/user-attachments/assets/60198e66-008e-425d-a22b-91ab64c04f7e" />

5. select `Build Credentials` > `All` (it will generate new credential and you can see it in Expo dashboard)
6. after generate complete select `go Back`

> In my project `eas.json`, our credentialsSource is set to 'local' so we have to do steps below,
> if it set to 'remote', maybe is done because it use remote credential and you just generated one.

8. select `credentials.json: Upload/Download`
9. select `Download` (and your `credentials.json` will have a new password)

ok, now run build --local again and it work fine with me.

**Comment by sipamungkas** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

it's 2025, you saved my life! After struggling more than 12 Hours.
Thanks!

**Comment by omerzirh** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

Appreciated. AI wont replace you :)

**Comment by jakubkanna** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).

This worked for me. I've installed it in the `system` keychain.

**Comment by garfieldcoked** [comment]
> I was experiencing the same problem. While trying to debug I manually downloaded the Distribution Certificate from the Credentials section on the EAS dashboard. When adding it to my macOS keychain (password is provided in .md file in the download) it shows the Certificate is untrusted.
> 
> Following this [thread](https://developer.apple.com/forums/thread/662300) I was missing [this](https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer) newer "Apple Worldwide Developer Relations Certification Authority" certificate. After adding this Apple certificate the distribution certificate is also trusted. Furthermore deleting the distribution certificate again and then running a `--local` iOS build successfully downloads the distribution certificate and gets added to the keychain.
> 
> I'm not sure, why this certificate is missing, as Apple states it [should have been updated with XCode](https://developer.apple.com/support/expiration/).


I was getting the following error when I tried the above:
> An error occurred. Unable to import “Apple Worldwide Developer Relations Certification Authority”. Error: -25294

This error means you likely have the expired version present and you need to manually deleted before installing the updated:

1. Open Keychain access app
2. Click View -> Show Expired Certificates
3. Search for "Worldwide"
4. If you see an expired version, delete it
5. Install AppleWWDRCAG3.cer

**Comment by sorinalinpavel** [comment]
curl -O https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer && security import AppleWWDRCAG3.cer -k ~/Library/Keychains/login.keychain-db && rm AppleWWDRCAG3.cer

then eas build --platform ios --local

**Comment by mhmmdpolatt** [comment]
> curl -O https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer && security import AppleWWDRCAG3.cer -k ~/Library/Keychains/login.keychain-db && rm AppleWWDRCAG3.cer
> 
> then eas build --platform ios --local

This issue has been driving me crazy for days! I did exactly what you said and the build finally started. Thank you so much, bro!

**Comment by mifi** [comment]
The workaround didn't work for me in CI (likely because expo creates its own new keychain for each build). What worked for me is editing `node_modules/@expo/build-tools/dist/ios/credentials/keychain.js` and removing `-v` from the `security find-identity` command. See #3679
