### ISSUE TITLE
Eas Build Failed: error Unable to resolve module ./App from /home/expo/workingdir/build/index.js:

### ISSUE THREAD

**Issue by pierre1590** [expo/eas-cli#1355]
### Build/Submit details page URL

https://expo.dev/accounts/pierre1590/projects/Cherry/builds/7e1b1c6f-dacf-4a05-93c5-2b44c0760e04

### Summary

eas.json:
```
{
  "cli": {
    "version": ">= 2.1.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```
I ran the command ` eas build -p android --profile preview` and then I get the following message:
```
        Welcome to Metro!
              Fast - Scalable - Integrated
[stderr] error Unable to resolve module ./App from /home/expo/workingdir/build/index.js:
[stderr] None of these files exist:
[stderr]   * App(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr]   * App/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr]   1 | import { registerRootComponent } from 'expo';
[stderr]   2 |
[stderr] > 3 | import App from './App';
[stderr]     |                  ^
[stderr]   4 |
[stderr]   5 | // registerRootComponent calls AppRegistry.registerComponent('main', () => App);
Error: Unable to resolve module ./App from /home/expo/workingdir/build/index.js: 
None of these files exist:
  * App(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * App/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  1 | import { registerRootComponent } from 'expo';
  2 |
> 3 | import App from './App';
[stderr]   6 | // It also ensures that whether you load the app in Expo Go or in a native build,.
    |                  ^
  4 |
  5 | // registerRootComponent calls AppRegistry.registerComponent('main', () => App);
  6 | // It also ensures that whether you load the app in Expo Go or in a native build,
    at ModuleResolver.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
at Object.resolve (/home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:317:42)
at resolve (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
info Run CLI with --verbose flag for more details.
> Task :app:bundleReleaseJsAndAssets FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.
[stderr] > Process 'command 'node'' finished with non-zero exit value 1
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 1m 10s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
21 actionable tasks: 21 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

### Managed or bare?

Managed

### Environment

npx expo-env-info:
 ```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```
expo doctor :
`  Didn't find any issues with the project! `

### Reproducible demo or steps to reproduce from a blank project

This is the first time I have encountered this type of error.

**Comment by wkozyra95** [comment]
This error means that there is no `App.js`/`App.ts`/... file, so building js bundle fails. Do you have that file?

**Comment by pierre1590** [comment]
Yes, that file is in src directory.

**Comment by pierre1590** [comment]
if I compile the project and then start with expo go it works, but when I try to build with eas build it fails with the error mentioned above.

**Comment by wkozyra95** [comment]
You might be defining a custom entry point somehow, that works in expo ecosystem, but when react-native builds your js code it does not respect those values.
e.g. https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in

**Comment by pierre1590** [comment]
I have tried this 

import { registerRootComponent } from 'expo';
import App from './src/App';

registerRootComponent(App);

But it doesn't function

**Comment by Toketec** [comment]
i have the same problem !!!!!

**Comment by lucas-dotshell** [comment]
Verify your .gitignore, <pt-BR>No meu caso, era simplismente um dos arquivos que estavam .no gitignore</pt-BR>

**Comment by josiaharkson** [comment]
I had a similar issue. Correcting a file path in my .gitignore file solved the problem.

Please check your .gitignore file and make sure all paths are correct.

**Comment by 563427956** [comment]
I may have a similar problem:

```javaScript 

[stderr] 
error Unable to resolve module ../config from /home/expo/workingdir/build/screens/Login.tsx: 
[stderr] 
None of these files exist:
[stderr] 
  * config(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr] 
  * config/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr] 
   8 | import {checkToken, Get, Post} from "../service/request";
[stderr] 
   9 | import AsyncStorage from '@react-native-async-storage/async-storage';
[stderr] 
> 10 | import Config from '../config';
[stderr] 
     |                     ^
[stderr] 
  11 | import {getGlobalData, setGlobalData} from "../service/global";
[stderr] 
  12 |
[stderr] 
  13 | export default function Login(props) {.
Error: Unable to resolve module ../config from /home/expo/workingdir/build/screens/Login.tsx: 
None of these files exist:
  * config(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * config/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
   8 | import {checkToken, Get, Post} from "../service/request";
   9 | import AsyncStorage from '@react-native-async-storage/async-storage';
> 10 | import Config from '../config';
     |                     ^
  11 | import {getGlobalData, setGlobalData} from "../service/global";
  12 |
  13 | export default function Login(props) {
    at ModuleResolver.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

But I've solved it. Try changing the **config** file name,

**Comment by Witillan** [comment]
> I may have a similar problem:
> 
> ```js
> [stderr] 
> error Unable to resolve module ../config from /home/expo/workingdir/build/screens/Login.tsx: 
> [stderr] 
> None of these files exist:
> [stderr] 
>   * config(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
> [stderr] 
>   * config/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
> [stderr] 
>    8 | import {checkToken, Get, Post} from "../service/request";
> [stderr] 
>    9 | import AsyncStorage from '@react-native-async-storage/async-storage';
> [stderr] 
> > 10 | import Config from '../config';
> [stderr] 
>      |                     ^
> [stderr] 
>   11 | import {getGlobalData, setGlobalData} from "../service/global";
> [stderr] 
>   12 |
> [stderr] 
>   13 | export default function Login(props) {.
> Error: Unable to resolve module ../config from /home/expo/workingdir/build/screens/Login.tsx: 
> None of these files exist:
>   * config(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
>   * config/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
>    8 | import {checkToken, Get, Post} from "../service/request";
>    9 | import AsyncStorage from '@react-native-async-storage/async-storage';
> > 10 | import Config from '../config';
>      |                     ^
>   11 | import {getGlobalData, setGlobalData} from "../service/global";
>   12 |
>   13 | export default function Login(props) {
>     at ModuleResolver.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
>     at DependencyGraph.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
>     at Object.resolve (/home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:129:24)
>     at resolve (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
>     at /home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
>     at Array.reduce (<anonymous>)
>     at resolveDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
>     at processModule (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> But I've solved it. Try changing the **config** file name,

Same problem here. It worked for me by changing the folder name "BachupScreen" to "Ba"

![image](https://github.com/expo/eas-cli/assets/56703868/4de1d7c6-3422-40da-ac66-b6cb4f592e7a)

**Comment by felipegith** [comment]
I have the same problem, but I solved change the name my folder

**Comment by LucasParra** [comment]
> @pierre1590 I had a similar issue. Correcting a file path in my .gitignore file solved the problem.
> 
> Please check your .gitignore file and make sure all paths are correct.

The file that was causing my error was listed in my .gitignore, I removed the entry in gitignore for the file and now is working fine

**Comment by actjacob** [comment]
Yes, the error could be caused by your .gitignore file.
#realtimedatabase
services/firebaseHelper.js
This line prevents your services/firebaseHelper.js file from being added to Git. If this file is not tracked by Git and you try to compile the project on another device or Expo server, you will get an error because this file is missing.


firstly download lenv library
->npm install react-native-dotenv

//.env.js
FIREBASE_API_KEY=your_api_key
FIREBASE_AUTH_DOMAIN=your_auth_domain
FIREBASE_PROJECT_ID=your_project_id


//firebaseHelper.js
import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getEnv } from 'react-native-dotenv';

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
};

const app = initializeApp(firebaseConfig);

return app;


Ok, now you are ready, your apikeys are stored safely and you can use your file.
