### ISSUE TITLE
EAS cannot create builds with Firebase and RN 0.69.5

### ISSUE THREAD

**Issue by yolpsoftware** [expo/eas-cli#1358]
### Build/Submit details page URL

https://expo.dev/accounts/yolpsoftware/projects/eas-firebase-test/builds/8729ce37-5e55-472c-8d11-8a20a6b9a143

### Summary

Since Expo SDK 46, my Firebase project cannot be built anymore by EAS. Both on cloud and local (`eas build --local`) I get a CocoaPods error. Since this is a Managed project, I cannot change anything in the Podfile.

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
    Expo Workflow: managed

expo doctor
🎉 Didn't find any issues with the project!

### Error output

[INSTALL_PODS] The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
[INSTALL_PODS] 
Error: pod exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/@expo/spawn-async/build/spawnAsync.js:41:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/@expo/turtle-spawn/dist/index.js:17:47)
    at installPods (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/@expo/build-tools/dist/ios/pod.js:12:38)
    at /Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/@expo/build-tools/dist/builders/ios.js:69:41
    at BuildContext.runBuildPhase (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/@expo/build-tools/dist/context.js:50:34)
    at buildAsync (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/@expo/build-tools/dist/builders/ios.js:68:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.iosBuilder (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/@expo/build-tools/dist/builders/ios.js:24:33)
    at async buildIosAsync (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/eas-cli-local-build-plugin/dist/ios.js:54:12)
    at async buildAsync (/Users/jo/.npm/_npx/b6b81adc32d91f4e/node_modules/eas-cli-local-build-plugin/dist/build.js:42:32)

### Reproducible demo or steps to reproduce from a blank project

https://github.com/yolpsoftware/eas-firebase-test

Check out the project, then run

```
eas build --platform ios --local
```

**Comment by wkozyra95** [comment]
`react-native-firebase` is not a library maintained by expo and neither it's included in a managed workflow. With problems like that you should post on the library repo.

With that said, it looks like they updated their documentation (for regular rn projects and for expo)
https://github.com/invertase/react-native-firebase/blob/main/docs/index.md#altering-cocoapods-to-use-frameworks

**Comment by almirfilho** [comment]
I'm having the same issue after upgrading to Expo 46 (from 45), and I'm not using `react-native-firebase` in my project.

```
npm ls react-native-firebase
project/path
└── (empty)
```

I do use `firebase` and `expo-firebase-analytics` though.

**Comment by wkozyra95** [comment]
@almirfilho Did you follow this part of instructions https://docs.expo.dev/versions/v46.0.0/sdk/firebase-analytics/#additional-configuration-for-ios ?

**Comment by VictorioMolina** [comment]
@almirfilho Same here. Did you find a solution?

**Comment by VictorioMolina** [comment]
Okey, this solves the problem: https://docs.expo.dev/versions/v46.0.0/sdk/firebase-analytics/#additional-configuration-for-ios
