### ISSUE TITLE
 JavaScript engine configuration is inconsistent between app.config.ts and Android native project.

### ISSUE THREAD

**Issue by rgonzalez-clicoh** [expo/eas-cli#1364]
### Summary

Hello People, I am having a problem with eas update, it tells me that there is inconsistency, which is not real

![3](https://user-images.githubusercontent.com/98822152/190462885-380dc459-2164-4235-b8d3-fe4023e56a4c.png)

It is exactly what is in the documentation

If I commented out the jsEngine it throws me the exception

![1](https://user-images.githubusercontent.com/98822152/190462878-8185f015-7c69-4436-9378-1e0957c9a167.png)

![2](https://user-images.githubusercontent.com/98822152/190462882-60497fa5-3d01-4da9-8b33-fecb8814bbd1.png)

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.3.11 => 0.3.11 
      @expo/webpack-config: ~0.16.21 => 0.16.27 
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Error output

[expo-cli] [13:48:54] JavaScript engine configuration is inconsistent between app.config.ts and Android native project.
[expo-cli] In app.config.ts: Hermes is not enabled
[expo-cli] In Android native project: Hermes is enabled
[expo-cli] Please check the following files for inconsistencies:
[expo-cli]   - app.config.ts
[expo-cli]   - android/gradle.properties
[expo-cli]   - android/app/build.gradle
[expo-cli] Learn more: https://expo.fyi/hermes-android-config
[expo-cli] [13:48:54] Error: JavaScript engine configuration is inconsistent between app.config.ts and Android native project.
[expo-cli] In app.config.ts: Hermes is not enabled
[expo-cli] In Android native project: Hermes is enabled
[expo-cli] Please check the following files for inconsistencies:
[expo-cli]   - app.config.ts
[expo-cli]   - android/gradle.properties
[expo-cli]   - android/app/build.gradle
[expo-cli] Learn more: https://expo.fyi/hermes-android-config
[expo-cli]     at maybeThrowFromInconsistentEngineAsync (node_modules/@expo/dev-server/src/HermesBundler.ts:112:11)
[expo-cli]     at maybeAddHermesBundleAsync (node_modules/@expo/dev-server/src/MetroDevServer.ts:214:5)
[expo-cli]     at bundleAsync (node_modules/@expo/dev-server/src/MetroDevServer.ts:247:26)
[expo-cli]     at Object.createBundlesAsync (node_modules/xdl/src/project/createBundlesAsync.ts:100:19)
[expo-cli]     at exportAppAsync (node_modules/expo-cli/src/commands/export/exportAppAsync.ts:85:19)
[expo-cli]     at exportFilesAsync (node_modules/expo-cli/src/commands/export/exportAsync.ts:99:10)
[expo-cli]     at actionAsync (node_modules/expo-cli/src/commands/export/exportAsync.ts:186:3)

### Reproducible demo or steps to reproduce from a blank project

"APP_ENV='staging' eas update --branch staging --platform='android'"

**Comment by rgonzalez-clicoh** [comment]
The problem is here, the regular expression is very exact... so if you have a linter for the gradlew files and you put single quotes in both hermes and jsc it will fail

This file: https://github.com/expo/expo/blob/main/packages/%40expo/dev-server/src/HermesBundler.ts

![image](https://user-images.githubusercontent.com/98822152/190491067-f407d40a-350c-434c-b647-7d6e8ed27ba2.png)
