### ISSUE TITLE
[Submitting build to TestFlight] An exception has occurred: issuerId is required

### ISSUE THREAD

**Issue by ChenCodes** [expo/eas-cli#1432]
Hi all - I recently finished a build of an iOS app. I then tried to upload the build to Testflight but am seeing the following issue in the logs:

> Waiting for submission to complete. You can press Ctrl+C to exit.
> ✖ Something went wrong when submitting your app to Apple App Store Connect.
> 
> We couldn't figure out what went wrong. See logs to learn more.
> 
> [logs] Starting iOS app upload
> [logs] Downloading archive
> [logs] Preparing artifact
> [logs] Verifying archive
> [logs] Creating ascApiJsonKey.json file with ASC credentials
> [logs] Uploading iOS app to TestFlight...
> [logs] Uploading the app with fastlane pilot
> [logs] -------------------
> [logs] --- Step: pilot ---
> [logs] -------------------
> [logs] Creating authorization token for App Store Connect API
> [logs] Ready to upload new build to TestFlight (App: 1611823656)...
> [logs] Going to upload updated app to App Store Connect
> [logs] This might take a few minutes. Please don't interrupt the script.
> [logs] Transporter transfer failed.
> [logs] 
> [logs] There was a general exception while executing
> [logs] An exception has occurred: issuerId is required
> [logs] [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [logs] 
> [logs] [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [logs] 
> [logs] [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [logs] 
> [logs] [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> [logs] [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:107)
> [logs] 
> [logs] [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:78)
> [logs] 
> [logs] [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)
> [logs] 
> [logs] [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [logs] 
> [logs] [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [logs] 
> [logs] [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [logs] [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> [logs] 
> [logs] [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:450)
> [logs] 
> [logs] [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)
> [logs] 
> [logs] [iTMSTransporter] 
> [logs] 
> [logs] [iTMSTransporter] [2022-10-10 10:12:06 PDT] <main> DBG-X: Returning 1
> [logs] 
> [logs] iTunes Transporter output above ^
> [logs] There was a general exception while executing
> [logs] An exception has occurred: issuerId is required
> [logs] Return status of iTunes Transporter was 1: There was a general exception \nAn exception has occurred: issuerId is required
> [logs] The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
> [logs] [!] Error uploading ipa file:
> [logs] Fastlane pilot failed
> [logs] Failed to submit the app
> [logs] Failed to upload the app
> 

I'd appreciate any help / suggestions! Please let me know if this isn't the right place to post as well.

**Comment by berkcoker** [comment]
Need to add the "appleId" field to eas.json. Looks like this is a new requirement, had the same issue

**Comment by nurimanizam** [comment]
> Need to add the "appleId" field to eas.json. Looks like this is a new requirement, had the same issue

I had to add the full details before it worked.

```
"submit": {
    "production": {
      "ios": {
        "appleId": "john@turtle.com",
        "ascAppId": "1234567890",
        "appleTeamId": "AB12XYZ34S"
      }
    }
  }
```

**Comment by DanialBetres** [comment]
I tried that but still doesn't work for me

**Comment by Taaqif** [comment]
Facing the same issue with eas-cli/2.3.0 win32-x64 node-v14.18.0

**Comment by onbrdsolutions** [comment]
Was facing the same issues. 
Managed to figure it out by defining the following
`"submit": {
    "production": {
      "ios": {       
        "ascApiKeyIssuerId": "2shfd6s-sfkjskjsf-qeuq9qe-example",
        "ascApiKeyPath": "AuthKey_934782Example.p8",
        "ascApiKeyId": "934782Example"
      },
    }
  }`

For anyone that needs to generate keys check this out [https://github.com/expo/fyi/blob/main/asc-issuer-id.md]

**Comment by feel2174** [comment]
where can i find "ascApiKeyPath",  "ascApiKeyId" ??

**Comment by mikgross** [comment]
Adding 
````
"appleId": "john@turtle.com",
"appleTeamId": "AB12XYZ34S"
````
under `submit: { production: { ios: {}}}` solved this issue

**Comment by dsokal** [comment]
This should be fixed now.

**Comment by fvalles** [comment]
Hi there! I am facing the same issue using fastlane with a React Native CLI application when I try to upload the app to Apple Store. Has someone found a solution? In which file `ascApiKeyId`, `ascApiKeyPath` and `ascApiKeyIssuerId` need to be added?

Thanks in advance

**Comment by dsokal** [comment]
@fvalles just upgrade Xcode to 14 :)

**Comment by shehanGuruge** [comment]
Hi, I am receiving this error,

```
Transporter transfer failed.
2022-10-20T08:24:17.5991900Z [08:24:17]: 
2022-10-20T08:24:17.6120110Z [08:24:17]: There was a general exception while executing
2022-10-20T08:24:17.6290480Z An exception has occurred: issuerId is required
2022-10-20T08:24:17.9693760Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-20T08:24:17.9694730Z 
2022-10-20T08:24:17.9695950Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T08:24:17.9696900Z 
2022-10-20T08:24:17.9698440Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T08:24:17.9698980Z 
2022-10-20T08:24:17.9700270Z [08:24:17]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2022-10-20T08:24:17.9701110Z 
2022-10-20T08:24:17.9702220Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:107)
2022-10-20T08:24:17.9702880Z 
2022-10-20T08:24:17.9704040Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:78)
2022-10-20T08:24:17.9705400Z 
2022-10-20T08:24:17.9706650Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)
2022-10-20T08:24:17.9708150Z 
2022-10-20T08:24:17.9708810Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-10-20T08:24:17.9709190Z 
2022-10-20T08:24:17.9709790Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T08:24:17.9710220Z 
2022-10-20T08:24:17.9710820Z [08:24:17]: [iTMSTransporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2022-10-20T08:24:17.9711250Z 
2022-10-20T08:24:17.9711970Z [08:24:17]: [iTMSTransporter] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2022-10-20T08:24:17.9712310Z 
2022-10-20T08:24:17.9713000Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.start(Application.java:450)
2022-10-20T08:24:17.9713410Z 
2022-10-20T08:24:17.9714020Z [08:24:17]: [iTMSTransporter] 	at com.apple.transporter.launcher.Application.main(Application.java:947)
2022-10-20T08:24:17.9714470Z 
2022-10-20T08:24:17.9714890Z [08:24:17]: [iTMSTransporter] 
2022-10-20T08:24:17.9715080Z 
2022-10-20T08:24:17.9716510Z [08:24:17]: [iTMSTransporter] [2022-10-20 08:24:17 UTC] <main> DBG-X: Returning 1
2022-10-20T08:24:17.9716920Z 
2022-10-20T08:24:17.9717550Z [08:24:17]: iTunes Transporter output above ^
2022-10-20T08:24:17.9718150Z [08:24:17]: There was a general exception while executing
2022-10-20T08:24:17.9719000Z An exception has occurred: issuerId is required
2022-10-20T08:24:17.9719660Z Return status of iTunes Transporter was 1: There was a general exception while executing
2022-10-20T08:24:17.9720300Z \nAn exception has occurred: issuerId is required
2022-10-20T08:24:17.9721480Z The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
2022-10-20T08:24:17.9924980Z 
2022-10-20T08:24:17.9926810Z [!] Error uploading ipa file: 
2022-10-20T08:24:17.9927310Z  
2022-10-20T08:24:18.0315070Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
2022-10-20T08:24:18.0339620Z ##[section]Finishing: Publish to the App Store TestFlight track
```

in azure pipelines. Anyway I could solve this? Issuer id is already defined in the service connection and also explicitly inside the AppStoreRelease@1 task.

**Comment by fvalles** [comment]
Thanks @dsokal ! Updating xcode did the trick! However, I have to mention that many errors arose after installing Xcode version 14.

If someone faces the following signing error after updating Xcode:

`error: Signing for "React-Core-AccessibilityResources" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'React-Core-AccessibilityResources' from project 'Pods')`

Try adding these lines to the Podfile in the post_install section:

```
installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
```

After doing this, I finally could build and publish iOS apps again! 🚀

**Comment by mikgross** [comment]
guys this is fixed. Update your xcode and expo version
