### ISSUE TITLE
Could not locate a valid AppDelegate at root

### ISSUE THREAD

**Issue by AmedeoOfficial** [expo/eas-cli#1559]
### Build/Submit details page URL

https://expo.dev/accounts/amedeoofficial/projects/Amedeo/builds/f303bf56-1e5a-4c65-abf2-d0032dcf2c75

### Summary

Hello! When I tried to build my expo app I received the following error: `withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"`. I haven't changed anything in my app that could trigger this problem since my last successful build, so i'm not sure what's going on. I have deleted the package-lock.json file from my project to fix a different unrelated eas bug, but I don't think that it matters. Any help would be much appreciated!

Things that I have tried:
- Installing the latest versions of @expo/config-plugins and @expo/prebuild-config
- Installing the latest version of expo-cli
- Installing the latest version of eas-cli

### Managed or bare?

Managed

### npx expo-env-info
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/metro-config: ^0.3.2 => 0.3.21
      expo: ^46.0.0 => 46.0.2
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.3 => 0.69.3
      react-native-web: ~0.18.7 => 0.18.7
    Expo Workflow: managed
### expo doctor
Expected package expo-modules-autolinking@~0.10.1
Found invalid:
  expo-modules-autolinking@0.8.1
  (for more info, run: npm why expo-modules-autolinking)
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^5.0.1
Found invalid:
  @expo/prebuild-config@4.0.4
  (for more info, run: npm why @expo/prebuild-config)
Some dependencies are incompatible with the installed expo package version:
 - @shopify/flash-list - expected version: 1.1.0 - actual version 
installed: 1.3.1
 - expo-av - expected version: ~12.0.4 - actual version installed: 12.0.3
 - expo-camera - expected version: ~12.4.0 - actual version installed: 12.3.0
 - expo-firebase-analytics - expected version: ~7.2.0 - actual version installed: 7.1.1
 - expo-firebase-core - expected version: ~5.2.0 - actual version 
installed: 5.1.1
 - expo-updates - expected version: ~0.14.7 - actual version installed: 0.14.3
 - react-native - expected version: 0.69.6 - actual version installed: 0.69.3
Your project may not work correctly until you install the correct 
versions of the packages.
To install the correct versions of these packages, please run: expo doctor --fix-dependencies,
or install individual packages by running expo install [package-name ...]
Warning: Invalid version react-native@0.69.3 for expo sdkVersion 46.0.0. Use react-native@0.69.6

### Error output

✖ Config sync failed
[stderr] [03:14:42] [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
[stderr] Please report this as an issue on https://github.com/expo/expo-cli/issues
[stderr] [03:14:42] UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
[stderr] Please report this as an issue on https://github.com/expo/expo-cli/issues
[stderr]     at getAppDelegateFilePath (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/ios/Paths.ts:52:11)
[stderr]     at getAppDelegate (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/ios/Paths.ts:114:20)
[stderr]     at Object.getSourceRoot (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/ios/Paths.ts:119:23)
[stderr]     at getProjectName (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:33:28)
[stderr]     at getIosNamedProjectPath (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:172:23)
[stderr]     at setIconsAsync (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:107:31)
[stderr]     at /Users/expo/workingdir/build/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:15:13
[stderr]     at action (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
[stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
[stderr]     at action (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27)
[stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at evalModsAsync (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
[stderr]     at compileModsAsync (/Users/expo/workingdir/build/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
[stderr]     at configureManagedProjectAsync (/Users/expo/workingdir/build/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
[stderr]     at prebuildAsync (/Users/expo/workingdir/build/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:90:21)
[stderr]     at actionAsync (/Users/expo/workingdir/build/node_modules/expo-cli/src/commands/prebuildAsync.ts:37:3)
[stderr] error Command failed with exit code 1.

### Reproducible demo or steps to reproduce from a blank project

I don't know how to create a reproducible demo for this kind of problem

**Comment by AmedeoOfficial** [comment]
For some reason, the problem seemed to just fix itself
