### ISSUE TITLE
Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. While trying to resolve module xx

### ISSUE THREAD

**Issue by a-eid** [expo/eas-cli#1599]
### Build/Submit details page URL

https://expo.dev/accounts/accubrew/projects/accupair/builds/783e7bab-ea4b-42b3-9bba-94c77a5c7ac1

### Summary

My android build is failing with this weird error even, the ios build is fine 

https://expo.dev/accounts/accubrew/projects/accupair/builds/16eb6bd7-9edb-418f-a676-5164fea65231

also everything is working locally just fine.

### Managed or bare?

managed

### Environment

```
expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.0.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.18.1 - ~/.n/bin/node
Yarn: 1.22.19 - ~/.yarn/bin/yarn
npm: 8.19.2 - ~/.n/bin/npm
Watchman: 4.9.0 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
Android SDK:
API Levels: 29, 30, 31, 32, 33
Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-31 | Google Play ARM 64 v8a
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8092744
Xcode: 14.1/14B47b - /usr/bin/xcodebuild
npmGlobalPackages:
eas-cli: 3.1.1
expo-cli: 6.0.8
Expo Workflow: managed
```

### Error output

```
[RUN_GRADLEW] Error: @build-script-error-begin
[RUN_GRADLEW] Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. While trying to resolve module `@accubrew/validation` from file `/private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/48a29854-429e-43f0-8d1d-d07544cd1cab/build/apps/mobile/src/screens/profile/sub-account-form.tsx`, the package `/private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/48a29854-429e-43f0-8d1d-d07544cd1cab/build/packages/validation/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/48a29854-429e-43f0-8d1d-d07544cd1cab/build/packages/validation/dist/index.js`. Indeed, none of these files exist:
[RUN_GRADLEW]   * /private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/48a29854-429e-43f0-8d1d-d07544cd1cab/build/packages/validation/dist/index.js(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
[RUN_GRADLEW]   * /private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/48a29854-429e-43f0-8d1d-d07544cd1cab/build/packages/validation/dist/index.js/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
[RUN_GRADLEW] @build-script-error-end
[RUN_GRADLEW]     at /private/var/folders/pk/1chfqnts1hz7gkfnp8j0jt380000gp/T/eas-build-local-nodejs/48a29854-429e-43f0-8d1d-d07544cd1cab/build/node_modules/expo-updates/scripts/createManifest.js:59:11
[RUN_GRADLEW]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[RUN_GRADLEW] > Task :expo-updates:createDebugExpoManifest FAILED
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':expo-updates:createDebugExpoManifest'.
[RUN_GRADLEW] >
[RUN_GRADLEW] Process 'command 'node'' finished with non-zero exit value 1
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] java.lang.StackOverflowError (no error message)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 3m 12s
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
[RUN_GRADLEW] Execution optimizations have been disabled for 3 invalid unit(s) of work during this build to ensure correctness.
[RUN_GRADLEW] Please consult deprecation warnings for more details.
[RUN_GRADLEW] 168 actionable tasks: 168 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by Hassanjankhan** [comment]
same problem

**Comment by crstnmac** [comment]
Same here with android build

```
[RUN_GRADLEW] Error: @build-script-error-begin
[RUN_GRADLEW] Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. index.js: Cannot find module '/private/var/folders/23/9hkxkgfd7bz7sqmykmtb0rbr0000gn/T/eas-build-local-nodejs/0d00904b-6677-43b6-8d1f-6f45110ae3da/build/node_modules/@tamagui/babel-plugin/dist/cjs'. Please verify that the package.json has a valid "main" entry
[RUN_GRADLEW] @build-script-error-end
[RUN_GRADLEW]     at /private/var/folders/23/9hkxkgfd7bz7sqmykmtb0rbr0000gn/T/eas-build-local-nodejs/0d00904b-6677-43b6-8d1f-6f45110ae3da/build/node_modules/expo-updates/scripts/createManifest.js:59:11
[RUN_GRADLEW]     at runMicrotasks (<anonymous>)
[RUN_GRADLEW]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
```

**Comment by TheRealMikeD** [comment]
Same problem here.  It is complaining about an image file that gets required in the code for a screen.  The image file exists in the place where it is specified, and it displays as expected in iOS.  Not sure why the Android build is choking on it.

**Comment by TRIAD-DEV** [comment]
Just sharing my problem too, my console where complaining about some archives that didn,t exist, after some time searching in the  project. I discovered that my archive -- import api from '../config'; -- where in my git.ignore file, so i removed from there and the problem was completely solved.
Output from the console:

`[stderr] Error: @build-script-error-begin
[stderr] Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. Unable to resolve module ../config from /home/expo/workingdir/build/src/repositories/Login.js: 
[stderr] None of these files exist:
[stderr]   * src/config(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr]   * src/config/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr] > 1 | import api from '../config';
[stderr]     |                  ^
[stderr]   2 | import { handleErrors, handlerResult } from './Service';
[stderr]   3 | import RastreabilidadeDao from '../services/RastreabilidadeDao';
[stderr]   4 |
[stderr] @build-script-error-end
[stderr]     at /home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:59:11
[stderr]     at runMicrotasks (<anonymous>)
[stderr]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> Task :expo-modules-core:generateReleaseRFile
> Task :app:bundleReleaseJsAndAssets FAILED`

**Comment by TheRealMikeD** [comment]
@TRIAD-DEV, it's starting to sound like the issue is with files that are in .gitignore.  Although, it may be that this is a problem with the Android SDK's build process, and not really with Expo or EAS.

**Comment by SpectorHacked** [comment]
Also having this issue with expo SDK 47, even through my app.json includes assetBundlePatterns to the assets, any solution?

**Comment by anirudhj111** [comment]
Facing a similar issue for eas build for development profile ,

**Comment by 1NoobDev** [comment]
I am having the same issues for images like @TheRealMikeD and @TRIAD-DEV .. Should a new issue be created for this to be looked into? 

### Issue
Build fails when the assets (or maybe even other dirs (untested)) are in the .gitignore file. 

OUTPUT:
```
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
```

```
> Task :app:createBundleReleaseJsAndAssets FAILED
Error: Unable to resolve module ../assets/onboarding/1.jpg from /home/expo/workingdir/build/src/screens/OnboardingScreen.js: 
None of these files exist:
  * 1.jpg
  * src/assets/onboarding/1.jpg/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  17 |             title: "Welcome to the App",
  18 |             text: "This is the first slide",
> 19 |             image: require('../assets/onboarding/1.jpg'),
     |                             ^
  20 |         },
```

### Solution
Removed the assets directory from the .gitignore, the build is **completed successfully**.
