### ISSUE TITLE
[ios build] Could not find 'bundler' (2.1.4)

### ISSUE THREAD

**Issue by ravi-poonia** [expo/eas-cli#172]
Just tried out the eas build for ios and getting the following error :

```

Fri, 18 Dec 2020 16:40:06 GMT
[stderr] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (2.1.4) required by your /usr/local/turtle-v2/src/services/worker/workingdir/build/ios/Gemfile.lock. (Gem::MissingSpecVersionError)
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] To update to the latest version installed on your system, run `bundle update --bundler`.
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] To install the missing version, run `gem install bundler:2.1.4`
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] Checked in 'GEM_PATH=/Users/expo/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
Fri, 18 Dec 2020 16:40:06 GMT
[stderr] 	from /usr/local/bin/fastlane:23:in `<main>'
Fri, 18 Dec 2020 16:40:06 GMT
Destroying keychain - /var/folders/97/73j93h690g9gdn54bh_zskm40000gn/T/turtle-v2-3fb707aa-f557-4140-9ada-46121386e3fb.keychain
Fri, 18 Dec 2020 16:40:10 GMT
Removing provisioning profile
Fri, 18 Dec 2020 16:40:10 GMT
Xcode build logs not found
Fri, 18 Dec 2020 16:40:10 GMT
Build failed: fastlane exited with non-zero code: 1
```

**Comment by ravi-poonia** [comment]
for anyone facing this issue in the future remove `fastlane` `Gemfile` and  `Gemfile.lock` from your `ios` directory
