### ISSUE TITLE
Error: While trying to resolve module `utils` from file `..` the package `../utils/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved .

### ISSUE THREAD

**Issue by a-eid** [expo/eas-cli#1741]
### Build/Submit details page URL

https://expo.dev/accounts/rcaraway101/projects/mobile/builds/282749cb-58de-422e-9448-ef575441ca87
https://expo.dev/accounts/rcaraway101/projects/mobile/builds/3382e364-1ff7-4634-8072-0106ed1c3978
https://expo.dev/accounts/accubrew/projects/accupair/builds/1c525586-3a02-458f-b4c4-0d7b8e62ea59

### Summary

this issue only happens when trying to build that app with eas, app is working perfectly in development.

#1599 

### Managed or bare?

managed.

### Environment

```bash
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - ~/.n/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - ~/.n/bin/npm
      Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: managed

```

```bash
➜  mobile git:(main) ✗ expo doctor
WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
🎉 Didn't find any issues with the project!
```

### Error output

```bash
> Task :app:createBundleReleaseJsAndAssets
Error: While trying to resolve module `utils` from file `/home/expo/workingdir/build/apps/mobile/App.tsx`, the package `/home/expo/workingdir/build/packages/utils/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/expo/workingdir/build/packages/utils/dist/utils.esm.js`. Indeed, none of these files exist:
  * /home/expo/workingdir/build/packages/utils/dist/utils.esm.js(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * /home/expo/workingdir/build/packages/utils/dist/utils.esm.js/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
    at DependencyGraph.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:272:17)
    at Object.resolve (/home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph._addDependency (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 1)
    at async Graph._processModule (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._traverseDependenciesForSingleFile (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/Graph.js:207:5)
[stderr] 
error While trying to resolve module `utils` from file `/home/expo/workingdir/build/apps/mobile/App.tsx`, the package `/home/expo/workingdir/build/packages/utils/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/expo/workingdir/build/packages/utils/dist/utils.esm.js`. Indeed, none of these files exist:
[stderr] 
  * /home/expo/workingdir/build/packages/utils/dist/utils.esm.js(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr] 
  * /home/expo/workingdir/build/packages/utils/dist/utils.esm.js/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
> Task :app:createBundleReleaseJsAndAssets FAILED

```

### Reproducible demo or steps to reproduce from a blank project

https://github.com/a-eid/eas-bug

**Comment by wkozyra95** [comment]
It works locally because you are building those libs separately, but on eas those libs are not compiled, so js files are missing.

Add ` "eas-build-post-install": "cd ../.. && yarn build" ` in app package.json in scripts section
