### ISSUE TITLE
[android build] Build error with @reactnativecommunity/async-storage

### ISSUE THREAD

**Issue by chernandez7** [expo/eas-cli#175]
Loving EAS so far! 

iOS built correctly but looks like my android build is running into an issue related to async storage. (Was installed with `expo install @react-native-async-storage/async-storage` on a managed project)

Any ideas if this is an issue on me end or with EAS? Let me know if I can provide more info.

Build ID: d78b3153-474b-44df-aa01-0e9e9251f762
Platform: Android
Username: alluxo

EAS Config:
```json
{
  "builds": {
    "android": {
      "release": {
        "workflow": "managed"
      }
    },
    "ios": {
      "release": {
        "workflow": "managed"
      }
    }
  }
}
```

Error Log: 
```sh
> Task :app:bundleReleaseJsAndAssets
Tue, 22 Dec 2020 03:59:37 GMT
info Writing bundle output to:, /build/src/services/worker/workingdir/build/android/app/build/generated/assets/react/release/index.android.bundle
Tue, 22 Dec 2020 03:59:37 GMT
info Writing sourcemap output to:, /build/src/services/worker/workingdir/build/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
Tue, 22 Dec 2020 03:59:37 GMT
info Done writing bundle output
Tue, 22 Dec 2020 03:59:37 GMT
info Done writing sourcemap output
Tue, 22 Dec 2020 03:59:39 GMT
info Copying 152 asset files
Tue, 22 Dec 2020 03:59:39 GMT
info Done copying assets
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:generatePackageList
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:preBuild
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:preReleaseBuild
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:mergeReleaseShaders
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:compileReleaseShaders
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:generateReleaseAssets
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:mergeReleaseAssets
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:copyReleaseBundledJs
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:compileReleaseRenderscript NO-SOURCE
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:generateReleaseResValues
Tue, 22 Dec 2020 03:59:40 GMT
> Task :app:generateReleaseResources
Tue, 22 Dec 2020 03:59:43 GMT
> Task :app:checkReleaseManifest
Tue, 22 Dec 2020 03:59:43 GMT
> Task :app:createReleaseCompatibleScreenManifests
Tue, 22 Dec 2020 03:59:43 GMT
> Task :app:mainApkListPersistenceRelease
Tue, 22 Dec 2020 03:59:43 GMT
> Task :app:processReleaseManifest
Tue, 22 Dec 2020 03:59:43 GMT
/build/src/services/worker/workingdir/build/android/app/src/main/AndroidManifest.xml:17:9-26:20 Warning:
Tue, 22 Dec 2020 03:59:43 GMT
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:17 to replace other declarations but no other declaration present
Tue, 22 Dec 2020 03:59:43 GMT
> Task :app:mergeReleaseResources
Tue, 22 Dec 2020 03:59:45 GMT
> Task :app:bundleReleaseResources
Tue, 22 Dec 2020 03:59:47 GMT
> Task :app:checkReleaseDuplicateClasses
Tue, 22 Dec 2020 04:00:03 GMT
> Task :app:desugarReleaseFileDependencies
Tue, 22 Dec 2020 04:00:03 GMT
> Task :app:compileReleaseAidl NO-SOURCE
Tue, 22 Dec 2020 04:00:03 GMT
> Task :app:generateReleaseBuildConfig
Tue, 22 Dec 2020 04:00:03 GMT
> Task :app:javaPreCompileRelease
Tue, 22 Dec 2020 04:00:06 GMT
> Task :app:bundleReleaseExpoConfig
Tue, 22 Dec 2020 04:00:09 GMT
> Task :app:createReleaseExpoManifest
Tue, 22 Dec 2020 04:00:09 GMT
                 Welcome to React Native!
Tue, 22 Dec 2020 04:00:09 GMT
                Learn once, write anywhere
Tue, 22 Dec 2020 04:00:36 GMT
> Task :app:mergeExtDexRelease
Tue, 22 Dec 2020 04:01:29 GMT
> Task :app:processReleaseResources
Tue, 22 Dec 2020 04:01:30 GMT
> Task :app:compileReleaseJavaWithJavac
Tue, 22 Dec 2020 04:01:31 GMT
> Task :app:transformClassesWithDexBuilderForRelease
Tue, 22 Dec 2020 04:01:31 GMT
> Task :app:processReleaseJavaRes NO-SOURCE
Tue, 22 Dec 2020 04:01:32 GMT
> Task :app:mergeReleaseJniLibFolders
Tue, 22 Dec 2020 04:01:33 GMT
> Task :app:mergeReleaseNativeLibs
Tue, 22 Dec 2020 04:01:34 GMT
> Task :app:mergeDexRelease
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] D8: Program type already present: com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] Program type already present: com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:198)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at java.lang.Thread.run(Thread.java:748)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.tools.r8.utils.t.a(:55)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.tools.r8.D8.run(:11)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	... 33 more
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.tools.r8.utils.Reporter.a(:21)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.tools.r8.utils.Reporter.a(:7)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	at com.android.tools.r8.utils.t.a(:36)
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] 	... 35 more
Tue, 22 Dec 2020 04:01:34 GMT
> Task :app:stripReleaseDebugSymbols
Tue, 22 Dec 2020 04:01:34 GMT
Support for ANDROID_NDK_HOME is deprecated and will be removed in the future. Use android.ndkVersion in build.gradle instead.
Tue, 22 Dec 2020 04:01:34 GMT
> Task :app:collectReleaseDependencies
Tue, 22 Dec 2020 04:01:34 GMT
> Task :app:mergeReleaseJavaResource
Tue, 22 Dec 2020 04:01:34 GMT
> Task :app:configureReleaseDependencies
Tue, 22 Dec 2020 04:01:34 GMT
> Task :app:validateSigningRelease
Tue, 22 Dec 2020 04:01:34 GMT
> Task :app:signingConfigWriterRelease
Tue, 22 Dec 2020 04:01:34 GMT
> Task :app:mergeDexRelease FAILED
Tue, 22 Dec 2020 04:01:34 GMT
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
Tue, 22 Dec 2020 04:01:34 GMT
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Tue, 22 Dec 2020 04:01:34 GMT
Use '--warning-mode all' to show the individual deprecation warnings.
Tue, 22 Dec 2020 04:01:34 GMT
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
Tue, 22 Dec 2020 04:01:34 GMT
838 actionable tasks: 838 executed
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] FAILURE: Build failed with an exception.
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] * What went wrong:
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] Execution failed for task ':app:mergeDexRelease'.
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Tue, 22 Dec 2020 04:01:34 GMT
[stderr]    > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Tue, 22 Dec 2020 04:01:34 GMT
[stderr]      Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Tue, 22 Dec 2020 04:01:34 GMT
[stderr]      Program type already present: com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] * Try:
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] * Get more help at https://help.gradle.org
Tue, 22 Dec 2020 04:01:34 GMT
[stderr] BUILD FAILED in 6m 16s
Tue, 22 Dec 2020 04:01:35 GMT
Build failed: ./gradlew exited with non-zero code: 1
```

**Comment by ravi-poonia** [comment]
This seems like a linking problem. A quick google search got me [this](https://github.com/react-native-async-storage/async-storage/issues/321)
See if this can help resolve your issue.

To check whether the EAS build will be successful or not, try to first assembleRelease in your local environment.

**Comment by chernandez7** [comment]
That would require ejecting / bare RN project correct? Thanks for the info.

**Comment by ravi-poonia** [comment]
I was assuming you were working with a bare project. If you're working with expo generated project then it says in the [documentation](https://docs.expo.io/build-reference/limitations/) that there might be some issues. Not sure. I guess they are still working on it.

**Comment by dsokal** [comment]
@chernandez7 
Hi, sorry for the very late response. Is this still an issue for you?

**Comment by chernandez7** [comment]
Currently can't confirm. Build blocked by a dependency relying on `@react-native-community/async-storage`. Once that issue is resolved will check again.

Issue for reference: https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/642

**Comment by mdebo** [comment]
@dsokal @react-native-community/async-storage moved to @react-native-async-storage/async-storage. This is a dependency of expo 41. Appsync javascript sdk uses @react-native-community/async-storage and therefore project using appsync javascript sdk cannot build for this latest expo version.

**Comment by brentvatne** [comment]
@chernandez7 - you should fork that dependency. `@react-native-community/async-storage` is not supported in SDK 41+, `@react-native-async-storage/async-storage` is required.
