### ISSUE TITLE
Unauthorized error when running eas build from CI

### ISSUE THREAD

**Issue by ferdytendie** [expo/eas-cli#1767]
### Summary

I am attempting to run `eas build` from an AWS CodePipeline. I run the following:

```
export EXPO_TOKEN=$(aws secretsmanager get-secret-value --secret-id "$EXPO_TOKEN_SECRET_NAME" | jq '.SecretString')

eas build --platform ios --non-interactive
```

and then I see the error

```
CombinedError: [Network] Unauthorized
    at makeErrorResult (/usr/local/
lib/node_modules/eas-cli/node_modules/@urql/core/dist/52541c06.js:231:10)
    at /usr/local/lib/node_modules/eas-cli/node_modules/@urql/core/dist/52541c06.js:393:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  graphQLErrors: [],
  networkError: Error: Unauthorized
      at /usr/local/lib/node_modules/eas-cli/node_modules/@urql/core/dist/52541c06.js:393:83
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5),
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://api.expo.dev/graphql',
      status: 401,
      statusText: 'Unauthorized',
      headers: [Headers],
      counter: 0
    }
  }
}

    Error: GraphQL request failed.
```

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 4.14 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 19.6.0 - ~/.nvm/versions/node/v19.6.0/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.4.0 - ~/.nvm/versions/node/v19.6.0/bin/npm
    npmGlobalPackages:
      expo-cli: 6.3.2
    Expo Workflow: managed

### Error output

```
CombinedError: [Network] Unauthorized
    at makeErrorResult (/usr/local/
lib/node_modules/eas-cli/node_modules/@urql/core/dist/52541c06.js:231:10)
    at /usr/local/lib/node_modules/eas-cli/node_modules/@urql/core/dist/52541c06.js:393:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  graphQLErrors: [],
  networkError: Error: Unauthorized
      at /usr/local/lib/node_modules/eas-cli/node_modules/@urql/core/dist/52541c06.js:393:83
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5),
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://api.expo.dev/graphql',
      status: 401,
      statusText: 'Unauthorized',
      headers: [Headers],
      counter: 0
    }
  }
}

    Error: GraphQL request failed.
```
### Reproducible demo or steps to reproduce from a blank project

Can't provide a simple repro without spinning up a whole AWS account.

**Comment by ferdytendie** [comment]
Figured it out -- the secrets manager command was adding quotes around the EXPO_TOKEN.
