### ISSUE TITLE
Eas build fails with local (on osX)

### ISSUE THREAD

**Issue by linaia** [expo/eas-cli#1773]
### Build/Submit details page URL

no build on expo (--local only)

### Summary

App works fine on real device with `npx expo run:android`
I need to build the app locally (not on expo), so I run with --local option :

`eas build --platform android --local --clear-cache --profile staging` 

it stops with Error: Invalid tag name (see detail above)

it is the same issue  than https://github.com/expo/eas-cli/issues/778 (but it was Windows)
 

### Managed or bare?

bare

### Environment

```
eas --version
eas-cli/3.9.0 darwin-x64 node-v16.20.0

npx expo-env-info
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/linaia/.npm/_logs/2023-04-06T16_17_33_956Z-debug.log
Install for [ 'expo-env-info@latest' ] failed with code 1
```

```
expo doctor
Expected package @expo/config-plugins@~6.0.0
Found invalid:
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
```
node --version
v16.20.0

npm --version
8.18.0

npx --version
10.2.2

### Error output

```
% eas build --platform android --local --clear-cache --profile staging
Specified value for "android.package" in app.config.js is ignored because an android directory was detected in the project.
EAS Build will use the value found in the native code.
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials xxxxxxx (default)
✔ Compressed project files 3s (12.9 MB)
/Users/linaia/.config/yarn/global/node_modules/npx/node_modules/npm-package-arg/npa.js:296
      throw invalidTagName(spec)
      ^

Error: Invalid tag name "eyJqb2IiOnsidHlwZSI... ZCJ9fQ==": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (/Users/linaia/.config/yarn/global/node_modules/npx/node_modules/npm-package-arg/npa.js:91:15)
    at fromRegistry (/Users/linaia/.config/yarn/global/node_modules/npx/node_modules/npm-package-arg/npa.js:296:13)
    at resolve (/Users/linaia/.config/yarn/global/node_modules/npx/node_modules/npm-package-arg/npa.js:81:12)
    at npa (/Users/linaia/.config/yarn/global/node_modules/npx/node_modules/npm-package-arg/npa.js:52:10)
    at Function.parseArgs (/Users/linaia/.config/yarn/global/node_modules/npx/node_modules/libnpx/parse-args.js:48:23)
    at Object.<anonymous> (/Users/linaia/.config/yarn/global/node_modules/npx/index.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  code: 'EINVALIDTAGNAME'
}
npx exited with non-zero code: 1
    Error: build command failed.
```

### Reproducible demo or steps to reproduce from a blank project

not yet

**Comment by dsokal** [comment]
Hi, what version of `eas-cli` do you have?

**Comment by linaia** [comment]
Thank you @dsokal, I had to reinstall node too and this error is gone.

I have also now npx exp-env-info result : 

```
npx expo-env-info
Need to install the following packages:
  expo-env-info@1.0.5
Ok to proceed? (y)

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.20.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
      Watchman: 2022.12.12.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.10 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    npmGlobalPackages:
      eas-cli: 3.9.0
      expo-cli: 6.0.8
    Expo Workflow: bare
```
