### ISSUE TITLE
EAS Update: cannot build

### ISSUE THREAD

**Issue by zdnk** [expo/eas-cli#1784]
### Summary

Hello, I am unable to build an update to publish to our users. I've never done it, this is the first time I tried.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.6.1 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.9 => 48.0.10 
      metro: ^0.73.7 => 0.73.9 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.4 => 0.71.4 
      react-native-web: ~0.18.9 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.9.1
    Expo Workflow: managed

### Error output

> % eas update --auto      
> [expo-cli] Starting Metro Bundler
> [expo-cli] Web Bundling failed 16144ms
> [expo-cli] Error: Unable to resolve module ../../Utilities/Platform from /Users/z/projects/<redacted>/app/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js: 
> [expo-cli] 
> [expo-cli] None of these files exist:
> [expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json|.web.svg|.native.svg|.svg)
> [expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform/index(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json|.web.svg|.native.svg|.svg)
> [expo-cli]   24 |
> [expo-cli]   25 | const {findNodeHandle} = require('../../ReactNative/RendererProxy');
> [expo-cli] > 26 | const Platform = require('../../Utilities/Platform');
> [expo-cli]      |                           ^
> [expo-cli]   27 | const React = require('react');
> [expo-cli]   28 | type ComponentRef = React.ElementRef<HostComponent<mixed>>;
> [expo-cli]   29 |
> [expo-cli] Error: Unable to resolve module ../../Utilities/Platform from /Users/z/projects/<redacted>/app/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js: 
> [expo-cli] 
> [expo-cli] None of these files exist:
> [expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json|.web.svg|.native.svg|.svg)
> [expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform/index(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json|.web.svg|.native.svg|.svg)
> [expo-cli]   24 |
> [expo-cli]   25 | const {findNodeHandle} = require('../../ReactNative/RendererProxy');
> [expo-cli] > 26 | const Platform = require('../../Utilities/Platform');
> [expo-cli]      |                           ^
> [expo-cli]   27 | const React = require('react');
> [expo-cli]   28 | type ComponentRef = React.ElementRef<HostComponent<mixed>>;
> [expo-cli]   29 |
> [expo-cli]     at ModuleResolver.resolveDependency (/Users/z/projects/<redacted>/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:137:15)
> [expo-cli]     at DependencyGraph.resolveDependency (/Users/z/projects/<redacted>/app/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
> [expo-cli]     at Object.resolve (/Users/z/projects/<redacted>/app/node_modules/metro/src/lib/transformHelpers.js:177:21)
> [expo-cli]     at Graph._resolveDependencies (/Users/z/projects/<redacted>/app/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
> [expo-cli]     at Graph._processModule (/Users/z/projects/<redacted>/app/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
> [expo-cli]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [expo-cli]     at async Graph._addDependency (/Users/z/projects/<redacted>/app/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
> [expo-cli]     at async Promise.all (index 1)
> [expo-cli]     at async Graph._processModule (/Users/z/projects/<redacted>/app/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
> [expo-cli]     at async Graph._addDependency (/Users/z/projects/<redacted>/app/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
> ✖ Export failed

### Reproducible demo or steps to reproduce from a blank project

Cant say how to reproduce.

**Comment by RashedMahyoub** [comment]
I've been having the same problem today. It doesn't give any error when using eas build but when trying to eas update, I get this error.

**Comment by quinlanj** [comment]
@zdnk just as a sanity check, could you make sure all your dependencies are up to date:
```
# remove all your dependencies
rm -rf node_modules 

# reinstall dependencies again
yarn # or npm install
```

then run `eas update --auto` again.

If you are still getting an error can you share your `package.json` please

**Comment by RashedMahyoub** [comment]
I don't know why but whenever I remove this part from app.json, eas update works

```
"web": {
      "bundler": "metro"
    }
```

**Comment by quinlanj** [comment]
Interesting. @zdnk could you try to clear the metro cache by running `npx expo start --clear`? Found [this](https://github.com/expo/expo/issues/13706#issuecomment-883783617) and it looks like relevant to your problem. It's a different binary than eas but they should all call into the metro bundler that shares the same metro cache at `$TMPDIR/metro-cache`

**Comment by quinlanj** [comment]
Closing due to inactivity

**Comment by quinlanj** [comment]
Update: I've landed https://github.com/expo/eas-cli/pull/1839 that will add the a `--clear-cache` flag to `eas update` to clear the metro bundler cache. It will be available in the next patch release of `eas-cli`.

**Comment by nilsm** [comment]
I'm getting the same error on a new Expo project - clearing the cache (or using the `--clear-cache` flag) hasn't worked.

eas build works fine.

```
eas-cli/4.1.2 darwin-arm64 node-v18.17.0
```

```
eas update --branch preview --message 'Updating the app' --clear-cache
```

Error:

```
[expo-cli] Experimental path aliases feature is enabled. Learn more: https://docs.expo.dev/guides/typescript/#path-aliases
[expo-cli] Starting Metro Bundler
[expo-cli] 
[expo-cli] warning: Bundler cache is empty, rebuilding (this may take a minute)
[expo-cli] 
[expo-cli] Error: Unable to resolve module ../Utilities/Platform from /Users/Documents/project/node_modules/react-native/Libraries/ReactNative/PaperUIManager.js: 
[expo-cli] 
[expo-cli] None of these files exist:
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform/index(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)
[expo-cli]   15 | const NativeModules = require('../BatchedBridge/NativeModules');
[expo-cli]   16 | const defineLazyObjectProperty = require('../Utilities/defineLazyObjectProperty');
[expo-cli] > 17 | const Platform = require('../Utilities/Platform');
[expo-cli]      |                           ^
[expo-cli]   18 | const UIManagerProperties = require('./UIManagerProperties');
[expo-cli]   19 |
[expo-cli]   20 | const viewManagerConfigs: {[string]: any | null} = {};
[expo-cli] Error: Unable to resolve module ../Utilities/Platform from /Users/Documents/project/node_modules/react-native/Libraries/ReactNative/PaperUIManager.js: 
[expo-cli] 
[expo-cli] None of these files exist:
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform/index(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css)
[expo-cli]   15 | const NativeModules = require('../BatchedBridge/NativeModules');
[expo-cli]   16 | const defineLazyObjectProperty = require('../Utilities/defineLazyObjectProperty');
[expo-cli] > 17 | const Platform = require('../Utilities/Platform');
[expo-cli]      |                           ^
[expo-cli]   18 | const UIManagerProperties = require('./UIManagerProperties');
[expo-cli]   19 |
[expo-cli]   20 | const viewManagerConfigs: {[string]: any | null} = {};
[expo-cli]     at ModuleResolver.resolveDependency (/Users/Documents/project/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
[expo-cli]     at DependencyGraph.resolveDependency (/Users/Documents/project/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
[expo-cli]     at Object.resolve (/Users/Documents/project/node_modules/metro/src/lib/transformHelpers.js:169:21)
[expo-cli]     at Graph._resolveDependencies (/Users/Documents/project/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
[expo-cli]     at Graph._processModule (/Users/Documents/project/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
[expo-cli]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[expo-cli]     at async Graph._addDependency (/Users/Documents/project/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
[expo-cli]     at async Promise.all (index 5)
[expo-cli]     at async Graph._processModule (/Users/Documents/project/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
[expo-cli]     at async Graph._addDependency (/Users/Documents/project/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
✖ Export failed
/Users/Documents/project/node_modules/expo/bin/cli exited with non-zero code: 1
```

**Comment by nilsm** [comment]
I ended up with the same error - for me it was a missing `platform` identifier in the update command. This did the trick:

```
eas update --platform android --branch preview --message 'Updating the app'
```

**Comment by BenBrownCreative** [comment]
Glad I stumbled across this thread. @nilsm's comment saved my day. Updating each platform separately in worked for me.

**Comment by joohnsro** [comment]
Hello @zdnk, I wish you had the same luck that I were today to did this app work.

After update like @quinlanj said, I did this command and works:
npx eas-cli update

Previously, I did this command and get the error:
eas update

I expect this could be usefull for somebody.

**Comment by azbub** [comment]
> @

this worked

> I don't know why but whenever I remove this part from app.json, eas update works
> 
> ```
> "web": {
>       "bundler": "metro"
>     }
> ```
