### ISSUE TITLE
Expo prebuild execution is not skipped automatically for bare projects.

### ISSUE THREAD

**Issue by mbaharan** [expo/eas-cli#1790]
### Summary

I have a bare workflow with custom functions implemented in Swift. I could run the native app before since the expo prebuild execution was skipped previously as the iOS folder existed in the project. Now I am getting the following error:
```
yarn run v1.22.17
$ /Users/expo/workingdir/build/node_modules/.bin/expo prebuild --no-install --platform ios
[stderr] 
The ios project is malformed, project files will be cleared and reinitialized.
- Clearing ios
✔ Cleared ios code
- Creating native project directories (./ios and ./android) and updating .gitignore
✔ Created native project | gitignore skipped
- Adding Metro bundler config
- Updating your package.json scripts, dependencies, and main file
✔ Updated package.json and added index.js entry point for iOS and Android
- Config syncing
✖ Config sync failed
[stderr] 
Error: [ios.dangerous]: withIosDangerousBaseMod: ENOENT: no such file or directory, open './assets/icon.png'
[stderr] 
Error: [ios.dangerous]: withIosDangerousBaseMod: ENOENT: no such file or directory, open './assets/icon.png'
[stderr] 
    at Object.openSync (node:fs:590:3)
[stderr] 
    at readFileSync (node:fs:458:35)
[stderr] 
    at calculateHash (/Users/expo/workingdir/build/node_modules/@expo/image-utils/build/Cache.js:14:91)
[stderr] 
    at createCacheKey (/Users/expo/workingdir/build/node_modules/@expo/image-utils/build/Cache.js:19:18)
[stderr] 
    at Object.createCacheKeyWithDirectoryAsync (/Users/expo/workingdir/build/node_modules/@expo/image-utils/build/Cache.js:24:33)
[stderr] 
    at generateImageAsync (/Users/expo/workingdir/build/node_modules/@expo/image-utils/build/Image.js:151:34)
[stderr] 
    at async setIconsAsync (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/build/plugins/icons/withIosIcons.js:169:15)
[stderr] 
    at async /Users/expo/workingdir/build/node_modules/@expo/prebuild-config/build/plugins/icons/withIosIcons.js:71:5
[stderr] 
    at async action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:23)
[stderr] 
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
[stderr] 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Unknown error. See logs for more information.
```
Since the iOS project folder is being initialized, the native app crashes on the phone as it doesn't have the custom functionality and permission already existing in `Info.plist`. I also set the icons in Xcode.
Is there any way to skip the "Prebuild" phase, as it is no longer skipped automatically as before?
Thanks in advance for any help. 

### Managed or bare?

Bare

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.4 - ~/Projects/nativeReact_iOS/FSC_FullStack/node_modules/.bin/npm
      Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.21 => 46.0.21 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.9 => 0.69.9 
      react-native-web: 0.18.7 => 0.18.7 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 3.9.2
      expo-cli: 6.3.2
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Not available.

**Comment by wkozyra95** [comment]
To detect if project is managed or bare we are checking for existence of `ios/testapp.xcodeproj/project.pbxproj` file, if the file does not exist or is gitignored we are treating the project as managed

**Comment by mbaharan** [comment]
Thanks for the reply. It's working now. The `project.pbxproj` changes between different team members, and that's why we've added it to `.gitignore`. It is just a suggestion but can a property be added to the `eas.json` in order to skip the rebuild phase?
Thanks

**Comment by buraks** [comment]
In my case, my `.gitignore` contains these

```
android/
ios/
```

So `eas build` doesn't upload my ios folder. However, I still get 

```
The ios project is malformed, project files will be cleared and reinitialized.
- Clearing ios
✔ Cleared ios code
- Creating native directory (./ios)
✔ Created native directory
- Updating package.json
✔ Updated package.json | no changes
- Running prebuild
✔ Finished prebuild
Running "bun install" in /Users/expo/workingdir/build/app directory
bun install v1.0.23 (83f2432d)

9 packages installed [25.00ms]
```

on the prebuild step. I would expect it to assume it's managed from the beginning. To avoid that I run `rm -rf android/ ios/`  before running `eas build` but it's an inconvenience. It's probably safe but I would feel more comfortable if there was a way to tell eas-cli to ignore the ios and android folders.

**Comment by phovious-14** [comment]
awesome, its worked for me 🎉

> To detect if project is managed or bare we are checking for existence of `ios/*.xcodeproj/project.pbxproj` file, if the file does not exist or is gitignored we are treating the project as managed
