### ISSUE TITLE
Android eas build throws error: Something went wrong while extracting the app from app archive

### ISSUE THREAD

**Issue by emilyseibert** [expo/eas-cli#1792]
### Summary

Without changing any setup to our builds, android has suddenly started failing installation on the android simulator with the above error: Error: Something went wrong while extracting the app from app archive

Here's our configuration that previously worked:
**eas.json**
```
{
  "build": {
    "local": {
      "node": "16.18.1",
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    },
  },
  "submit": {
    "production": {}
  },
  "cli": {
    "version": "3.7.2"
  }
}

   ```
**Build command**
```EAS_LOCAL_BUILD_SKIP_CLEANUP=1 EAS_LOCAL_BUILD_ARTIFACTS_DIR=build-tarballs RCT_NO_LAUNCH_PACKAGER=1 eas build --local --clear-cache --non-interactive --json --clear-cache --platform android --profile local --output build-tarballs/android-local.tar.gz"```

**Installation command**
```eas build:run --path build-tarballs/android-local.tar.gz --platform android```

**eas-cli version**
3.7.2 (but I've also tried 3.9.1 with the same error)

### Managed or bare?

Managed

### Environment

```  
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
      Yarn: 3.2.2 - ~/.nvm/versions/node/v18.14.2/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
      Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 33
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0
        System Images: android-30 | Google APIs ARM 64 v8a
        Android NDK: 25.2.9519653
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.7.2
    Expo Workflow: managed
```

```
❯ npx expo-doctor
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

Didn't find any issues with the project!
```

### Error output

```
    Error: Something went wrong while extracting the app from app archive
Error: Command failed:  EXPO_DEBUG=true eas build:run --path build-tarballs/android-local.tar.gz --platform android
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at createSyncProcess (/Users/emilyseibert/src/universal-cds/node_modules/nx/src/executors/run-commands/run-commands.impl.js:166:34)
    at /Users/emilyseibert/src/universal-cds/node_modules/nx/src/executors/run-commands/run-commands.impl.js:113:13
    at Generator.next (<anonymous>)
    at /Users/emilyseibert/src/universal-cds/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/emilyseibert/src/universal-cds/node_modules/tslib/tslib.js:114:16)
    at runSerially (/Users/emilyseibert/src/universal-cds/node_modules/nx/src/executors/run-commands/run-commands.impl.js:111:20) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 76589,
  stdout: null,
  stderr: null
```

### Reproducible demo or steps to reproduce from a blank project

Using the build commands above with the eas.json config.

**Comment by dsokal** [comment]
Hi,

I think the issue here is that the internal distribution on Android produces an .apk file, and with `--output build-tarballs/android-local.tar.gz` you change the extension of that file. What happens here is that `eas build:run` checks the extension of the artifact and tries to unarchive it because it's `.tar.gz` while it's actually `.apk`.

Try dropping the `--output build-tarballs/android-local.tar.gz` argument from `eas build` and check what's in `build-tarballs` (actually the dirname is misleading).

**Comment by emilyseibert** [comment]
```
EAS_LOCAL_BUILD_SKIP_CLEANUP=1 EAS_LOCAL_BUILD_ARTIFACTS_DIR=build-tarballs RCT_NO_LAUNCH_PACKAGER=1 eas build --local --clear-cache --non-interactive --json --clear-cache --platform android --profile local
```

This resolves the installation error! I've reviewed our git history and we were definitely using tarballs for android with eas 3.4.1. I'm not sure what's changed between these two versions, but it seems android tarballs are no longer working but this is a fine enough workaround for our purposes. Thanks!
