### ISSUE TITLE
Builds for Android not working on Expo 48 with production profile

### ISSUE THREAD

**Issue by feRpicoral** [expo/eas-cli#1819]
### Build/Submit details page URL

https://expo.dev/accounts/anonime/projects/anonime/builds/9e56eed7-eee1-4e7d-89c3-6ca55bdd452d

### Summary

After updating Expo SDK to version 48, I cannot create builds for Android for production. Funny enough, when using the development profile, the build completes with no errors. Builds for iOS work fine, regardless of the profile. The builds fail locally and on Expo servers, with the exact same error.

Everything works with no errors when running on Expo GO or using the development build.

My entry file is `./src/index.ts` and I set `"main": "./src/index"` on `package.json`. Before updating to the SDK 48, I had the same path ("./src/index") as the `entryPoint` of my `app.config.ts`.

Here's my `eas.json` file:

```json
{
  "cli": {
    "version": ">=3.5.2",
    "requireCommit": true
  },
  "build": {
    "development": {
      "channel": "development",
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      },
      "android": {
        "buildType": "apk"
      }
    },
    "production": {
      "channel": "production",
      "env": {
        "API_URL": "https://example.com"
      }
    }
  }
}

```

### Managed or bare?

Managed

### Environment

`npx expo-env-inf`
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/fpicoral/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Electric Eel 2022.1.1 Patch 1 Electric Eel 2022.1.1 Patch 1
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.15 => 48.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
    npmGlobalPackages:
      eas-cli: 3.10.2
    Expo Workflow: managed
```

`npx expo-doctor`
```
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

Didn't find any issues with the project!
```

### Error output

```
[RUN_GRADLEW] Error: @build-script-error-begin
[RUN_GRADLEW] Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point.
[RUN_GRADLEW] @build-script-error-end
[RUN_GRADLEW]     at /private/var/folders/yz/pnkbfxnx7cdflsjq6bx811w80000gn/T/eas-build-local-nodejs/cd466cb8-5684-48be-88fa-02d30e778bce/build/node_modules/expo-updates/scripts/createManifest.js:36:11
[RUN_GRADLEW]     at Object.<anonymous> (/private/var/folders/yz/pnkbfxnx7cdflsjq6bx811w80000gn/T/eas-build-local-nodejs/cd466cb8-5684-48be-88fa-02d30e778bce/build/node_modules/expo-updates/scripts/createManifest.js:99:3)
[RUN_GRADLEW]     at Module._compile (node:internal/modules/cjs/loader:1126:14)
[RUN_GRADLEW]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
[RUN_GRADLEW]     at Module.load (node:internal/modules/cjs/loader:1004:32)
[RUN_GRADLEW]     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
[RUN_GRADLEW]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[RUN_GRADLEW]     at node:internal/main/run_main_module:17:47
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':expo-updates:createReleaseExpoManifest'.
[RUN_GRADLEW] > Process 'command 'node'' finished with non-zero exit value 1
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] java.lang.StackOverflowError (no error message)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 53s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

```

**Comment by feRpicoral** [comment]
I found a workaround:

The `index` **must** be `index.js` instead of `index.ts`, and it **must** be at the root of the project - it can't be in `.src/...`.

I still believe this is a bug, especially since it was working fine on the previous SDK.

**Comment by wkozyra95** [comment]
https://docs.expo.dev/build-reference/migrating/#custom-main-entry-point-in-packagejson-is-not-supported

**Comment by JordanDDisch** [comment]
this looks like an easy fix? Or might just be something with people locals? 

https://github.com/expo/expo/blob/main/packages/expo-updates/scripts/createManifest.js#L35

like why does setting the ENTRY_FILE not work? `ENTRY_FILE=index.native.tsx eas build --platform android --local`

Please explain away my ignorance here.

**Comment by feRpicoral** [comment]
> https://docs.expo.dev/build-reference/migrating/#custom-main-entry-point-in-packagejson-is-not-supported

Yes, but the problem was not this. Even following the instructions on the docs, it only started working when I moved `index.ts` to `index.js`. I'm still using a `index.js` file since and don't plan on trying to convert it back to typescript.

Not sure if this bug is still present, but it is indeed a bug. This problem was only happening with android and I didn't change anything other than the file extension.

**Comment by DAVIS-PYTH** [comment]
Hello @feRpicoral 

I'm experiencing this issue too. Any solution yet

**Comment by feRpicoral** [comment]
> Hello @feRpicoral 
> 
> 
> 
> I'm experiencing this issue too. Any solution yet

Check the workaround I mentioned earlier in the thread. That's what I'm using since I found it, no problems with it so far.
