### ISSUE TITLE
iOS build fails on "Prepare project" step with 403

### ISSUE THREAD

**Issue by ShaneMcNamara** [expo/eas-cli#1820]
### Build/Submit details page URL

https://expo.dev/accounts/ontraccr/projects/OnTraccr-Alpha/builds/ecf3c340-57b7-4a48-9062-46adf89eb840

### Summary

When I try to build the app using `eas build` the iOS version fails on the "Prepare project" step with the following error:

```
Failed to download project archive
Failed to download the file: Response code 403 (Forbidden)
HTTPError: Response code 403 (Forbidden)
    at Request._onResponseBase (/usr/local/eas-build-worker/node_modules/got/dist/source/core/index.js:905:31)
    at Request._onResponse (/usr/local/eas-build-worker/node_modules/got/dist/source/core/index.js:940:24)
    at ClientRequest.<anonymous> (/usr/local/eas-build-worker/node_modules/got/dist/source/core/index.js:954:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at ClientRequest.origin.emit (/usr/local/eas-build-worker/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
```

Android build works fine.

### Managed or bare?

managed

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.21.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.3 - /Users/ShaneMcNamara/.rvm/gems/ruby-2.2.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.21 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.9 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.6.0
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by szdziedzic** [comment]
Hi,

EAS Build was experiencing network issues on May 2nd (please see https://status.expo.dev/ for more information). Your problem is related to it. It looks like it started to work fine in your most recent build. You can follow our status page to keep up to date with the updates about this partial outage.
