### ISSUE TITLE
iOS entitlement "com.apple.developer.in-app-payments" has invalid value 

### ISSUE THREAD

**Issue by EtherealData** [expo/eas-cli#1895]
### Build/Submit details page URL

https://expo.dev/accounts/indiepro/projects/indie-pro/builds/a6523f2c-5639-41fe-807b-822650b602c4

### Summary

I have tried adding the correct entry in app.json

```
"entitlements": {
        "com.apple.developer.in-app-payments": ["merchant.app.indiepro"]
      },
```
When I try to `eas build -p ios --profile production` I get the error

```
✔ Logged in Local session
✔ Bundle identifier registered app.indiepro.mobile.ios
✔ Synced capabilities: Enabled: Sign In with Apple
✖ Failed to sync capability identifiers app.indiepro.mobile.ios
iOS entitlement "com.apple.developer.in-app-payments" has invalid value "merchant.app.indiepro,IndiePro". Expected an array of strings, where each string is prefixed with "merchant.", ex: ["merchant.myapp"]
```

It's as if my  array `["merchant.app.indiepro"]` somehow gets joined into this string with extra `,IndiePro`

I tried as well to disable the capability sync, which lets it build but then fails during fastlane step.

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.13.0 - ~/.npm-modules/bin/yarn
      npm: 6.14.17 - ~/workspaces/indie-pro-mobile/node_modules/.bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.0 
      expo: ~48.0.10 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.14.0
    Expo Workflow: managed
    ```
    ```
      expo-doctor@1.1.1
Ok to proceed? (y) y
✔ Check package.json for common issues
✖ Check for conflicting global packages in project
Unexpected error while running 'Check for conflicting global packages in project' check:
Error: Dependency tree validation for expo-cli failed. This validation is only available on Node 16+ / npm 8.
✖ Check for incompatible packages
Unexpected error while running 'Check for incompatible packages' check:
Error: Dependency tree validation for react-native-unimodules failed. This validation is only available on Node 16+ / npm 8.
✔ Validate global prerequisites versions
✖ Validate Expo Config
✖ Verify prebuild support package versions are compatible
Unexpected error while running 'Verify prebuild support package versions are compatible' check:
Error: Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
✖ Check compatible dependency versions for the installed Expo SDK

Detailed check results:

Some dependencies are incompatible with the installed expo version:
  expo-image@1.2.3 - expected version: ~1.0.1
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install expo-image@~1.0.1
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

Error: Problems validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • should NOT have additional property 'facebookScheme'.
 • should NOT have additional property 'facebookAppId'.
 • should NOT have additional property 'facebookDisplayName'.
    ```
    I don't know why some checks fail, I am running node 18

### Error output

```
limitless$ EXPO_DEBUG=true yarn build
yarn run v1.13.0
$ eas build -p ios --profile production
ios.infoPlist: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosInfoPlistBaseMod
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withVersion ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withBuildNumber ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withUsesNonExemptEncryption ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withScheme ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withRequiresFullScreen ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withOrientation ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withDisplayName ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withGoogle ➜ withInfoPlist
ios.infoPlist: withStaticPlugin ➜ withRunOnce ➜ withLocation ➜ withInfoPlist
ios.infoPlist: withStaticPlugin ➜ withRunOnce ➜ withImagePicker ➜ withInfoPlist
ios.infoPlist: withStaticPlugin ➜ withRunOnce ➜ withDevClient ➜ withGeneratedIosScheme ➜ withInfoPlist
ios.infoPlist: withSplashScreen ➜ withIosSplashScreen ➜ withPlugins ➜ withStaticPlugin ➜ withIosSplashInfoPlist ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosUserInterfaceStyle ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosRootViewBackgroundColor ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosFacebook ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosBranch ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosAdMob ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withMaps ➜ withGoogleMapsKey ➜ withInfoPlist
ios.infoPlist: withStaticPlugin ➜ withRunOnce ➜ withAppleAuth ➜ withAppleAuthIOS ➜ withIOSMixedLocales ➜ withInfoPlist
ios.entitlements: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosEntitlementsBaseMod
ios.entitlements: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withAssociatedDomains ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withExpoDocumentPicker ➜ withStaticPlugin ➜ withRunOnce ➜ withDocumentPickerIOS ➜ withEntitlementsPlist
ios.entitlements: withExpoNotifications ➜ withStaticPlugin ➜ withRunOnce ➜ withNotifications ➜ withNotificationsIOS ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withExpoContacts ➜ withRunOnce ➜ withAccessesContactNotes ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withRunOnce ➜ withStripe ➜ withStripeIos ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withRunOnce ➜ withAppleAuth ➜ withAppleAuthIOS ➜ withEntitlementsPlist
ios.expoPlist: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosExpoPlistBaseMod
ios.expoPlist: withExpoUpdates ➜ withStaticPlugin ➜ withRunOnce ➜ withUpdates ➜ withUpdates ➜ withExpoPlist
ios.splashScreenStoryboard: withPlugins ➜ withStaticPlugin ➜ withIosSplashScreenStoryboardBaseMod ➜ withGeneratedBaseMods ➜ withIosSplashScreenStoryboardBaseMod
ios.splashScreenStoryboard: withSplashScreen ➜ withIosSplashScreen ➜ withPlugins ➜ withStaticPlugin ➜ withIosSplashScreenImage ➜ withIosSplashScreenStoryboard
ios.podfileProperties: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosPodfilePropertiesBaseMod
ios.podfileProperties: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withJsEnginePodfileProps ➜ withPodfileProperties

Expo Metro config:
- Version: 0.7.1
- Extensions: ts, tsx, js, jsx, json
- React Native: /Users/limitless/workspaces/indie-pro-mobile/node_modules/react-native
- Babel config: /Users/limitless/workspaces/indie-pro-mobile/babel.config.js
- Resolver Fields: react-native, browser, main
- Watch Folders: 
- Node Module Paths: 
- Exotic: false

✔ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: …HIDDEN
› Restoring session HIDDEN
› Team HIDDEN
› Provider HIDDEN
✔ Logged in Local session
- Linking bundle identifier app.indiepro.mobile.ios
✔ Bundle identifier registered app.indiepro.mobile.ios
- Syncing capabilities
Current remote capabilities:
[
  {
    "context": {
      "providerId": 118058900,
      "teamId": "7UFV6P7LZP"
    },
    "id": "K2R6CSLFZ7_IN_APP_PURCHASE",
    "attributes": {
      "ownerType": "BUNDLE",
      "settings": null,
      "editable": true,
      "inputs": null,
      "enabled": true,
      "responseId": "315e82fd-024e-4f62-a465-d556c3e831f0"
    }
  },
  {
    "context": {
      "providerId": 118058900,
      "teamId": "7UFV6P7LZP"
    },
    "id": "K2R6CSLFZ7_PUSH_NOTIFICATIONS",
    "attributes": {
      "ownerType": "BUNDLE",
      "settings": null,
      "editable": true,
      "inputs": null,
      "enabled": true,
      "responseId": "315e82fd-024e-4f62-a465-d556c3e831f0"
    }
  },
  {
    "context": {
      "providerId": 118058900,
      "teamId": "7UFV6P7LZP"
    },
    "id": "K2R6CSLFZ7_APPLE_ID_AUTH",
    "attributes": {
      "ownerType": "BUNDLE",
      "settings": [
        {
          "key": "APPLE_ID_AUTH_APP_CONSENT",
          "options": [
            {
              "key": "PRIMARY_APP_CONSENT",
              "properties": [
                null
              ]
            }
          ]
        }
      ],
      "editable": true,
      "inputs": null,
      "enabled": true,
      "responseId": "315e82fd-024e-4f62-a465-d556c3e831f0"
    }
  },
  {
    "context": {
      "providerId": 118058900,
      "teamId": "7UFV6P7LZP"
    },
    "id": "K2R6CSLFZ7_APPLE_PAY",
    "attributes": {
      "ownerType": "BUNDLE",
      "settings": null,
      "editable": true,
      "inputs": null,
      "enabled": true,
      "responseId": "315e82fd-024e-4f62-a465-d556c3e831f0"
    }
  }
]

Current local entitlements:
{
  "com.apple.developer.in-app-payments": [
    "merchant.app.indiepro",
    "IndiePro"
  ],
  "aps-environment": "development",
  "com.apple.developer.applesignin": [
    "Default"
  ]
}
Skipping existing capability: com.apple.developer.in-app-payments (Apple Pay Payment Processing)
Remaining to remove:  [
  'K2R6CSLFZ7_IN_APP_PURCHASE',
  'K2R6CSLFZ7_PUSH_NOTIFICATIONS',
  'K2R6CSLFZ7_APPLE_ID_AUTH'
]
Skipping existing capability: aps-environment (Push Notifications)
Remaining to remove:  [ 'K2R6CSLFZ7_IN_APP_PURCHASE', 'K2R6CSLFZ7_APPLE_ID_AUTH' ]
Existing to disable:  [ 'K2R6CSLFZ7_IN_APP_PURCHASE', 'K2R6CSLFZ7_APPLE_ID_AUTH' ]
Patch Request: [ { capabilityType: 'APPLE_ID_AUTH', option: 'ON' } ]
✔ Synced capabilities: Enabled: Sign In with Apple
- Syncing capabilities identifiers
✖ Failed to sync capability identifiers app.indiepro.mobile.ios
iOS entitlement "com.apple.developer.in-app-payments" has invalid value "merchant.app.indiepro,IndiePro". Expected an array of strings, where each string is prefixed with "merchant.", ex: ["merchant.myapp"]
Error: iOS entitlement "com.apple.developer.in-app-payments" has invalid value "merchant.app.indiepro,IndiePro". Expected an array of strings, where each string is prefixed with "merchant.", ex: ["merchant.myapp"]
    at assertValidOptions (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/appstore/bundleIdCapabilities.js:117:15)
    at validate (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/appstore/capabilityIdentifiers.js:46:59)
    at syncCapabilityIdentifiersForEntitlementsAsync (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/appstore/capabilityIdentifiers.js:51:14)
    at syncCapabilityIdentifiersAsync (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/appstore/ensureAppExists.js:91:117)
    at syncCapabilitiesAsync (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/appstore/ensureAppExists.js:80:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ensureBundleIdExistsWithNameAsync (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/appstore/ensureAppExists.js:58:9)
    at async AppStoreApi.ensureBundleIdExistsAsync (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/appstore/AppStoreApi.js:42:16)
    at async SetUpTargetBuildCredentials.runAsync (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/actions/SetUpTargetBuildCredentials.js:18:13)
    at async SetUpBuildCredentials.runAsync (/Users/limitless/.nvm/versions/node/v18.16.0/lib/node_modules/eas-cli/build/credentials/ios/actions/SetUpBuildCredentials.js:49:60)
    Error: build command failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducible demo or steps to reproduce from a blank project

I am not sure how to reproduce easily. Can anyone run `eas build -p ios --profile production` successfully as of the latest eas-cli version?

**Comment by EtherealData** [comment]
For anyone dealing with same issue and using stripe - This is where the conflicting came from.. I just removed the entitlements section and renamed the `merchantIdentifier` to the correct value

```
   "plugins": [
      "expo-apple-authentication",
      [
        "@stripe/stripe-react-native",
        {
          "merchantIdentifier": "merchant.app.indiepro",
          "enableGooglePay": true
        }
      ]
    ],
```
