### ISSUE TITLE
Last version of EAS CLI breaks Android build.

### ISSUE THREAD

**Issue by elenitaex5** [expo/eas-cli#1951]
### Build/Submit details page URL

https://expo.dev/accounts/elenitaex5/projects/proapp/builds/b79c6596-0670-400d-8fc2-9f7fcdc5e409

### Summary

I have been creating my builds (both Android and iOS) with EAS perfectly right till version `eas-cli@3.13.3` and I thing 3.14.X too.
But since I upgrade to versions `3.16.X` and `3.17.0` my app is crashing. EAS BUILD and submission seems to be ok, but the app crashed since the beginning. 

Problem comes because new versions of `eas-cli` is editing `AndroidManifest.xml` changing as it said in this issue comment
https://github.com/expo/expo/issues/21238#issuecomment-1636277775

This is the  error shown when app crashes:
```
java.lang.AssertionError: The embedded manifest is invalid or could not be read. Make sure you have configured expo-updates correctly in android/app/build.gradle. null
	at expo.modules.updates.manifest.EmbeddedManifest.get(EmbeddedManifest.kt:34)
	at expo.modules.updates.launcher.NoDatabaseLauncher.<init>(NoDatabaseLauncher.kt:70)
	at expo.modules.updates.launcher.NoDatabaseLauncher.<init>(NoDatabaseLauncher.kt:23)
	at expo.modules.updates.UpdatesController.start(UpdatesController.kt:238)
	at expo.modules.updates.UpdatesController$Companion.initialize(UpdatesController.kt:506)
	at expo.modules.updates.UpdatesPackage$createReactNativeHostHandlers$handler$1.onWillCreateReactInstanceManager(UpdatesPackage.kt:46)
	at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:27)
	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
	at com.abiglobalhealth.proapp.MainApplication.onCreate(MainApplication.java:66)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1278)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7092)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Managed or bare?

Bare

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.4 => 18.1.2 
      expo: ~48.0.18 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.17.0
      expo-cli: 6.3.10
    Expo Workflow: bare
    ```

✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

Upgrading a wellformed project from eas-cli 3.13.X or 3.14.X to 3.16.X or 3.17.X

**Comment by tomhendra** [comment]
Try this...

https://github.com/expo/expo/issues/23599#issuecomment-1641991609

**Comment by superjose** [comment]
Same here

**Comment by Pakvothe** [comment]
+1

**Comment by Guiladg** [comment]
+1

**Comment by pavelbabenko** [comment]
I fixed the issue with adding `expo.updates.url` (https://exp.host/[organization]/[project]) in app.json

**Comment by superjose** [comment]
> I fixed the issue with adding `expo.updates.url` (https://exp.host/[organization]/[project]) in app.json

I'll try this out. 

Thanks for letting us know!!!

We managed to push the app out using was cli v 1.1.1.

**Comment by superjose** [comment]
> I fixed the issue with adding `expo.updates.url` ([https://exp.host/[organization]/[project]](https://exp.host/%5Borganization%5D/%5Bproject%5D)) in app.json

I have to confirm this is working. 

Currently on Expo SDK 46.

**Comment by Goowwy** [comment]
> I fixed the issue with adding `expo.updates.url` ([https://exp.host/[organization]/[project]](https://exp.host/%5Borganization%5D/%5Bproject%5D)) in app.json

please post here , link is not working
