### ISSUE TITLE
EAS Authentication with Apple Developer Portal failed! Apple provided the following error info: You are not registered as an Apple Developer.  

### ISSUE THREAD

**Issue by codergautam** [expo/eas-cli#2048]
### Build/Submit details page URL

https://expo.dev/accounts/codergautamyt/projects/barbosa

### Summary

A non-technical founder invited me to his App Store Connect team so I can code, build, and submit his app for him. App is done building and I want to submit build into App Store Connect. I can open the app fine on App store connect but when I try to submit the build I get this error.

I personally don't have Apple Developer on this account but I should still be able to submit right? I can provide team or provider ID if needed.

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
      npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed
\✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@2.0.4
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.

### Error output

Loaded "env" configuration for the "production" profile: no environment variables specified. Learn more
Error: Cannot find module 'expo-dev-client/package.json'
Require stack:
- /Users/codergautam/Documents/projects/barbosa/noop.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at resolveFileName (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/resolve-from/index.js:46:47)
    at isExpoDevClientInstalledAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/build/build/utils/devClient.js:68:36)
    at ensureExpoDevClientInstalledForDevClientBuildsAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/build/build/utils/devClient.js:18:15)
    at runBuildAndSubmitAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/build/build/runBuildAndSubmit.js:65:79)
    at async Build.runAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/build/commands/build/index.js:41:9)
    at async Build._run (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js:272:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/codergautam/Documents/projects/barbosa/noop.js' ]
}
ios.infoPlist: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosInfoPlistBaseMod
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withVersion ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withBuildNumber ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withUsesNonExemptEncryption ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withScheme ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withRequiresFullScreen ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withOrientation ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withDisplayName ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withGoogle ➜ withInfoPlist
ios.infoPlist: withSplashScreen ➜ withIosSplashScreen ➜ withPlugins ➜ withStaticPlugin ➜ withIosSplashInfoPlist ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosUserInterfaceStyle ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosRootViewBackgroundColor ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosBranch ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosAdMob ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withMaps ➜ withGoogleMapsKey ➜ withInfoPlist
ios.infoPlist: withStaticPlugin ➜ withRunOnce ➜ withVoice ➜ withIosPermissions ➜ withInfoPlist
ios.infoPlist: withStaticPlugin ➜ withRunOnce ➜ withAuth0 ➜ withIOSAuth0InfoPList ➜ withInfoPlist
ios.entitlements: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosEntitlementsBaseMod
ios.entitlements: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withAssociatedDomains ➜ withEntitlementsPlist
ios.entitlements: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withNotificationsEntitlement ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withExpoContacts ➜ withRunOnce ➜ withAccessesContactNotes ➜ withEntitlementsPlist
ios.entitlements: withStaticPlugin ➜ withExpoAppleAuthentication ➜ withRunOnce ➜ withAppleSignInWarning ➜ withEntitlementsPlist
ios.expoPlist: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosExpoPlistBaseMod
ios.expoPlist: withStaticPlugin ➜ withRunOnce ➜ withUnversionedUpdates ➜ withUpdates ➜ withExpoPlist
ios.splashScreenStoryboard: withPlugins ➜ withStaticPlugin ➜ withIosSplashScreenStoryboardBaseMod ➜ withGeneratedBaseMods ➜ withIosSplashScreenStoryboardBaseMod
ios.splashScreenStoryboard: withSplashScreen ➜ withIosSplashScreen ➜ withPlugins ➜ withStaticPlugin ➜ withIosSplashScreenImage ➜ withIosSplashScreenStoryboard
ios.podfileProperties: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosPodfilePropertiesBaseMod
ios.podfileProperties: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withJsEnginePodfileProps ➜ withPodfileProperties

Expo Metro config:
- Version: 0.10.7
- Extensions: ts, tsx, js, jsx, json, cjs
- React Native: /Users/codergautam/Documents/projects/barbosa/node_modules/react-native
- Babel config: /Users/codergautam/Documents/projects/barbosa/babel.config.js
- Resolver Fields: react-native, browser, main
- Watch Folders: 
- Node Module Paths: 
- Exotic: false
- Env Files: .env.local,.env
- Sass: null

✔ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … codergautam@yahoo.com
› Restoring session /Users/codergautam/.app-store/auth/codergautam@yahoo.com/cookie
› Session expired Local session
› Using password for codergautam@yahoo.com from your local Keychain
  Learn more
✔ Logged in New session
Authentication with Apple Developer Portal failed!
Apple provided the following error info:
You are not registered as an Apple Developer.  Please visit Apple Developer Registration. https://developer.apple.com/register/
UnexpectedAppleResponse: Apple provided the following error info:
You are not registered as an Apple Developer.  Please visit Apple Developer Registration. https://developer.apple.com/register/
    at Object.y [as parseAppStoreResponse] (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:846029)
    at p (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:850508)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.selectTeamAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:850780)
    at async t.validateSessionAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:738507)
    at async Object.S [as loginWithUserCredentialsAsync] (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:709939)
    at async loginWithUserCredentialsAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:84:24)
    at async loginAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:56:16)
    at async authenticateAsUserAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:129:27)
    at async authenticateAsync (/Users/codergautam/.nvm/versions/node/v20.5.1/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:101:16) {
  errorInfo: {
    responseId: 'd79dde80-ba2b-4b82-bceb-da2b82cb5505',
    resultCode: 2100,
    resultString: 'You are not registered as an Apple Developer.  Please visit Apple Developer Registration. https://developer.apple.com/register/',
    userString: 'You are not registered as an Apple Developer.  Please visit Apple Developer Registration. https://developer.apple.com/register/',
    creationTimestamp: '2023-09-06T23:37:05Z',
    protocolVersion: 'QH65B2',
    userLocale: 'en_US',
    requestUrl: 'https://developer.apple.com/services-account/QH65B2/account/listTeams.action',
    httpCode: 200
  },
  data: undefined
}
    Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

Be invited to a team on your account which is not in Apple Developer program. Run eas build -p ios in a fresh new Expo project.

**Comment by bdotsamir** [comment]
I actually have this same issue and I wonder if this is something EAS would be able to support in the future. Theoretically, I could upload the project files to App Store Connect. I have permission to- I was given the Admin role. The only question then becomes can I _sign_ the app as an Admin? Or is that capability only granted to people who have paid Developer accounts?
