### ISSUE TITLE
Failed to autodetect applicationId in multi-flavor project

### ISSUE THREAD

**Issue by talaikis** [expo/eas-cli#2133]
### Summary

Trying to build Android project with flavors gives the following error, although it works fine outside EAS.

```
Unable to read gradle project config: flavor dev is not defined.
Values from app/build.gradle might be resolved incorrectly.
Specified value for "android.package" in app.json is ignored because an android directory was detected in the project.
EAS Build will use the value found in the native code.
Failed to autodetect applicationId in multi-flavor project
```

### Managed or bare?

Bare

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20230709.023423.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 33, 34
        Build Tools: 28.0.3, 30.0.3, 33.0.0, 33.0.1, 34.0.0
        System Images: android-27 | Google Play Intel x86 Atom, android-33 | Google Play Intel x86 Atom_64, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-212.5712.43.2112.8815526
    npmPackages:
      expo: 49.0.16 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: bare
```

### Error output

```
AmbiguousApplicationIdError: Failed to autodetect applicationId in multi-flavor project.
    at getApplicationIdFromBareAsync (node_modules\eas-cli\build\project\android\applicationId.js:62:19)
    at async createAndroidContextAsync (node_modules\eas-cli\build\build\android\build.js:44:27)
    at async createBuildContextAsync (node_modules\eas-cli\build\build\createContext.js:91:22)
    at async prepareAndStartBuildAsync (node_modules\eas-cli\build\build\runBuildAndSubmit.js:169:22)
    at async runBuildAndSubmitAsync (node_modules\eas-cli\build\build\runBuildAndSubmit.js:83:49)
    at async Build.runAsync (node_modules\eas-cli\build\commands\build\index.js:41:9)
    at async Build._run (node_modules\eas-cli\node_modules\@oclif\core\lib\command.js:80:22)
    at async Config.runCommand (node_modules\eas-cli\node_modules\@oclif\core\lib\config\config.js:272:25)
    at async Object.run (node_modules\eas-cli\node_modules\@oclif\core\lib\main.js:74:5)
```

### Reproducible demo or steps to reproduce from a blank project

```
flavorDimensions "default"
    productFlavors {
        create("dev") {
            applicationId "com.xxx.dev"
            resValue "string", "app_name", "xxx"
            resValue "string", "build_config_package", "com.xxx"
        }
        create("stag") {
            applicationId "com.xxx.stag"
            resValue "string", "app_name", "xxx"
            resValue "string", "build_config_package", "com.xxx"
        }
        create("prod") {
            applicationId "com.xxx.prod"
            resValue "string", "app_name", "xxx"
            resValue "string", "build_config_package", "com.xxx"
        }
    }
```

**Comment by ThomasBizeta** [comment]
Have you managed to fix this issue? I'm encountering right now and I have no clue on how to fix it. Android studio's build works just fine but eas-cli doesnt

**Comment by talaikis** [comment]
> Have you managed to fix this issue? I'm encountering right now and I have no clue on how to fix it. Android studio's build works just fine but eas-cli doesnt

No, had little time to dig into it.

**Comment by alecananian** [comment]
@ThomasBizeta what does your `eas.json` and `productFlavors` look like? I had the same error message and got this working with the following:

**build.gradle**
```
productFlavors {
    production {
        dimension "profile"
        applicationId "..."
    }
    preview {
        dimension "profile"
        applicationId "..."
    }
}
```

**eas.json**
```
"build": {
  "preview": {
    ...
    "android": {
      "gradleCommand": ":app:bundlePreviewRelease"
    },
  },
  "production": {
    ...
    "android": {
      "gradleCommand": ":app:bundleProductionRelease"
    },
  }
},
```

The key for me was to make sure `flavorDimensions` was a string, not an array (even though Android Studio gives a deprecation warning) and use specify the `gradleCommand` in the config.

**Comment by talaikis** [comment]
Ok, the fix is straightforward, remove "applicationIdSuffix" and add "applicationId"

**Comment by ThomasBizeta** [comment]
> Ok, the fix is straightforward, remove "applicationIdSuffix" and add "applicationId"

My eas.json and productFlavors are basically the same as yours
`    flavorDimensions 'Variants'
    productFlavors {
        'xxx' {
            dimension 'Variants'
            applicationId "xxx.xxx.xxx"
        }
        'yyy' {
            dimension 'Variants'
            applicationId 'yyy.yyy.yyy'
        }
        'zzz' {
            dimension 'Variants'
            applicationId 'zzz.zzz.zzz'
        }
    }`
    
   ```
"android": {
        "gradleCommand": ":app:assembleyyyRelease"
      },
```
