### ISSUE TITLE
Can't submit to Apple App Store, Apple 403 detected - Access forbidden.

### ISSUE THREAD

**Issue by lennartkloock** [expo/eas-cli#2136]
### Summary

When executing `eas submit -p ios` and selecting an eas build and providing the right path to the Apple Connect API key, I get:
```
Error: Apple 403 detected - Access forbidden.
This request is forbidden for security reasons - The API key in use does not allow this request
✖ Failed to fetch App Store Connect API Key.
Apple 403 detected - Access forbidden.
This request is forbidden for security reasons - The API key in use does not allow this request
    Error: submit command failed.
```

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.17.1 - /usr/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.6.7 - /usr/bin/npm
    npmPackages:
      expo: ~45.0.8 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: bare

### Error output

at t.getAppleResponseError (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:833596)
    at block (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:840893)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async I (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:839166)
    at async method (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:840374)
    at async t.providerRequestAsync (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:734446)
    at async s.requestAsync (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:740890)
    at async s.requestAndParseAsync (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:741594)
    at async s.fetchSingleModelAsync (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:741360)
    at async getAscApiKeyAsync (/usr/lib/node_modules/eas-cli/build/credentials/ios/appstore/ascApiKey.js:38:24)
...

### Reproducible demo or steps to reproduce from a blank project

Can't share a demo

**Comment by szdziedzic** [comment]
Hi, is that how you generated the API key https://github.com/expo/fyi/blob/main/creating-asc-api-key.md?

**Comment by lennartkloock** [comment]
> Hi, is that how you generated the API key https://github.com/expo/fyi/blob/main/creating-asc-api-key.md?

Yes, that's exactly how I did it. When `eas submit` asks for the path, I provide the path to the `.p8` file

**Comment by lennartkloock** [comment]
Could you provide a link to the source code of the `apple-utils` package so I can investigate myself. I can't find it anywhere. 🤔

**Comment by lennartkloock** [comment]
I tried submitting with an app-specific password using the `EXPO_APPLE_APP_SPECIFIC_PASSWORD` env var and it worked

**Comment by wellRoundedAppDev** [comment]
hello any solutions? Help

**Comment by Aniganesh** [comment]
I'm having the same issue myself. Has there been a resolution other than using app specific password?

**Comment by mbrodt** [comment]
I was unable to get it working just by providing the .p8 file and the key ID when running eas submit, but I then added the keys to eas.json and it worked:

```
 "submit": {
    "production": {
      "ios": {
        "ascApiKeyPath": "./path_to_file",
        "ascApiKeyIssuerId": "",
        "ascApiKeyId": ""
      }
    }
  }
```

**Comment by MuhammadHussnainShaker** [comment]
I did not had the permissions on my Apple Developer Account to generate App Store Connect API keys so uploading the app's .ipa through Transporter worked for me. Refer to this link for more details on uploading app to App Store Connect:
https://developer.apple.com/help/app-store-connect/manage-builds/upload-builds/

**Comment by saursharma** [comment]
I was facing the same issue. I had uploaded the App store connect API key to expo dev account but submission was failing.
However it was working fine if I was providing it in eas.json file. 

To resolve, I just update eas.json file ascAppId field. Example:

```
"submit": {
  "production": {
    "ios": {
      "ascAppId": "XXX"
    }
  }
}
```

It worked fine after this.

**Comment by nimesh-oss** [comment]
> I was facing the same issue. I had uploaded the App store connect API key to expo dev account but submission was failing. However it was working fine if I was providing it in eas.json file.
> 
> To resolve, I just update eas.json file ascAppId field. Example:
> 
> ```
> "submit": {
>   "production": {
>     "ios": {
>       "ascAppId": "XXX"
>     }
>   }
> }
> ```
> 
> It worked fine after this.

do we have build again?

**Comment by luckywacky** [comment]
Found the actual root cause after a lot of back-and-forth — it's not (only) about the API key's own role.

Everyone here (including Expo's own [creating-asc-api-key.md](https://github.com/expo/fyi/blob/main/creating-asc-api-key.md) guide) correctly says the key itself needs Admin role. But even with a correctly-configured Admin-role key, eas credentials still 403s on both "connect an existing key" and "generate a brand new key" — same error either way.

Turns out there's a second, independent permission gate: the role of the person's own Apple ID membership on the Apple Developer team, separate from the API key's role. In our case, the Apple ID logged into eas credentials had App Manager (or lower) as its own account role on the team — enough to manage certificates, provisioning profiles, and push keys through the same session (those all worked fine), but the "Users and Access → Integrations → App Store Connect API" section of App Store Connect is gated to people with Admin membership, regardless of what role you assign to any key.

So the checklist should be:

The API key itself: Admin role ✅ (as documented)
The person logged into eas credentials's own membership role on the team: also needs to be Admin — App Manager/Developer isn't enough, even though it's enough for actual eas submit and cert/profile management.

If you're hitting this and your key is already Admin, check your own account's role under App Store Connect → Users and Access → People — not the key's role, your own. Elevating that (or having whoever's already Admin run eas credentials once) resolved it for us.

One more thing that tripped us up: once the key is registered this way, you don't need any ios submit config in eas.json at all — no ascApiKeyPath, ascApiKeyId, ascApiKeyIssuerId, or even ascAppId. eas submit resolves everything from the credential stored on EAS's servers and the project's bundle identifier automatically.
