### ISSUE TITLE
undefined method `__apply_Xcode_12_5_M1_post_install_workaround' for #<Pod::Podfile:0x000000012e038ae8>

### ISSUE THREAD

**Issue by omardiaa** [expo/eas-cli#2194]
### Build/Submit details page URL

https://expo.dev/accounts/omar_/projects/Chemistry-School/builds/b38ade78-bc7c-48be-a75d-b24b74eedd75

### Summary

I am trying to build the app using `eas build -p ios --clear-cache` but it fails in "Install Pods" step with the following error: 
```
[!] An error occurred while processing the post-install hook of the Podfile.
undefined method `__apply_Xcode_12_5_M1_post_install_workaround' for #<Pod::Podfile:0x000000012e038ae8>
```

### Managed or bare?

Managed

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 20.10.0 - ~/node/bin/node
      Yarn: 1.22.21 - ~/node/bin/yarn
      npm: 10.2.4 - ~/node/bin/npm
    npmPackages:
      expo: ^49.0.21 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.1 => 0.73.1 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed
    
    ----------------
    
    ✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that native modules do not use incompatible support packages

Detailed check results:

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~6.2.4
Found invalid:
  @expo/prebuild-config@5.0.7
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Some dependencies are incompatible with the installed expo version:
  @react-native-async-storage/async-storage@1.21.0 - expected version: 1.18.2
  expo-device@5.6.0 - expected version: ~5.4.0
  expo-permissions@14.4.0 - expected version: ~14.2.1
  expo-screen-capture@5.5.0 - expected version: ~5.3.0
  expo-screen-orientation@6.2.0 - expected version: ~6.0.6
  react-native@0.73.1 - expected version: 0.72.6
  react-native-gesture-handler@2.14.0 - expected version: ~2.12.0
  react-native-reanimated@3.6.1 - expected version: ~3.3.0
  react-native-safe-area-context@4.8.2 - expected version: 4.6.3
  react-native-screens@3.29.0 - expected version: ~3.22.0
  react-native-webview@13.6.4 - expected version: 13.2.2
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

### Error output

```

/Users/expo/workingdir/build/ios/Podfile:66:in `block (3 levels) in from_ruby'
/Users/expo/.gems/arm64/gems/cocoapods-core-1.12.1/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:149:in `message'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:183:in `integrate'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:170:in `install!'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/expo/.gems/arm64/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/expo/.gems/arm64/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/expo/.gems/arm64/bin/pod:25:in `load'
/Users/expo/.gems/arm64/bin/pod:25:in `<main>'
[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `3389EE6F606F44B4BB710E49` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod install exited with non-zero code: 1
```

### Reproducible demo or steps to reproduce from a blank project

Run `eas build -p  ios`, it fails on "Install Pods" step.

**Comment by szdziedzic** [comment]
Hi there 👋!

I think this function was removed in RN 0.73 🤔 

SDK 49 is configured to use RN 0.72 by default and that's why it's failing 🤔 

What I would suggest here to resolve this issue is to:
1. Try to resolve all of your `expo doctor` warnings. It says that `react-native@0.73.1 - expected version: 0.72.6`. You can run `npx expo install --fix` to fix it.
2. Update to SDK 50 https://expo.dev/changelog/2024/01-18-sdk-50

**Comment by ichivers** [comment]
Using expo 50.0.0 & react-native 0.73.6.  Still get this error when running eas build --platform ios --local 

[INSTALL_PODS] [!] An error occurred while processing the post-install hook of the Podfile.
[INSTALL_PODS] undefined method `__apply_Xcode_12_5_M1_post_install_workaround' for an instance of Pod::Podfile

**Comment by domenicoprestia** [comment]
try to follow the resolution in this issue, it worked for me
https://github.com/facebook/react-native/issues/42070
