### ISSUE TITLE
eas submit error "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by BrandonMathis** [expo/eas-cli#2389]
### Summary

Running `eas submit --platform ios` throws an error in my console and no new submissions are made on the Expo account.

```
🐚 eas submit --platform ios

✔ What would you like to submit? › Select a build from EAS
✔ Which build would you like to submit? › - ID: xxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxx (3 days ago)
Ensuring your app exists on App Store Connect. This step can be skipped by providing ascAppId in the submit
profile. Learn more: https://expo.fyi/asc-app-id

› Log in to your Apple Developer account to continue
✔ Apple ID: … xxx@xxxxxx.com
› Restoring session /Users/xxxxxxxxx/.app-store/auth/xx@xxxxxx.com/cookie
✔ Select a Team › XXXXXXXXXX XXXXXXXXXXX Inc - Company/Organization (XXXXXXXXXXXX)
› Provider XXXXXXXXX XXXXXXXXXX Inc (XXXXXXXXX)
✔ Logged in Local session

Cannot read properties of undefined (reading 'attributes')
Submission failed
    Error: submit command failed.
```

Running with `DEBUG=*` did not provide many details

```
✔ Logged in Local session

Cannot read properties of undefined (reading 'attributes')
Submission failed
Error: Submission failed
    at IosSubmitCommand.resolveSubmissionOptionsAsync (/Users/xxxxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/submit/ios/IosSubmitCommand.js:58:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IosSubmitCommand.runAsync (/Users/xxxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/submit/ios/IosSubmitCommand.js:39:25)
    at async withAnalyticsAsync (/Users/xxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/analytics/common.js:7:24)
    at async submitAsync (/Users/xxxxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/submit/submit.js:17:12)
    at async Submit.runAsync (/Users/xxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/commands/submit.js:58:32)
    at async Submit._run (/Users/xxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/Users/xxxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js:301:25)
```

### Managed or bare?

Managed

### Environment

```
 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.16.0/bin/yarn
      npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.6
      expo: ^51.0.5 => 51.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    npmGlobalPackages:
      eas-cli: 9.0.7
    Expo Workflow: managed
```

### Error output

```
✔ Logged in Local session

Cannot read properties of undefined (reading 'attributes')
Submission failed
Error: Submission failed
    at IosSubmitCommand.resolveSubmissionOptionsAsync (/Users/xxxxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/submit/ios/IosSubmitCommand.js:58:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IosSubmitCommand.runAsync (/Users/xxxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/submit/ios/IosSubmitCommand.js:39:25)
    at async withAnalyticsAsync (/Users/xxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/analytics/common.js:7:24)
    at async submitAsync (/Users/xxxxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/submit/submit.js:17:12)
    at async Submit.runAsync (/Users/xxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/build/commands/submit.js:58:32)
    at async Submit._run (/Users/xxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/Users/xxxxxxxxxxx/.asdf/installs/nodejs/18.16.0/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js:301:25)
```

### Reproducible demo or steps to reproduce from a blank project

`eas submit --platform ios`

**Comment by AmitayCohen1** [comment]
Same here

**Comment by brentvatne** [comment]
hey folks, @kadikraman and i have tried to reproduce this and were unable to.

- does `eas build -p ios` work for you?
- are you using an ASC API key to handle submissions? or an app specific password?
- if you run `eas credentials -p ios` and go to "App Store Connect: Manage your API Key" and generate a key from there, does that work for you?

**Comment by BrandonMathis** [comment]
@brentvatne The `eas build` command works for me. [Here is a link to a recent build I enqueued using it](https://expo.dev/accounts/brandonmathis/projects/goplaysave-mobile-v2/builds/e6e7d4df-09a5-42a1-8f8d-7f95e784d8ea)

I used the `eas credentials -p ios` command to deleted my existing key I used for eas submit & generated a new key. After that, the problem persists with the same error

**Comment by szdziedzic** [comment]
@BrandonMathis Can you try to do `rm -rf ~/.app-store` to clear the cache?

**Comment by szdziedzic** [comment]
@BrandonMathis what is the output of `cat ~/.app-store/auth/apple-developer-portal-domain.json` on your device?

**Comment by quinlanj** [comment]
@BrandonMathis when was the last time you logged in, before you ran `eas submit --platform ios` and saw the error?

**Comment by AmitayCohen1** [comment]
Solved! 
I added to eas.json in the submit.production.ios the
- ascAppId
- appleId
- appleTeamId

**Comment by BrandonMathis** [comment]
> @BrandonMathis what is the output of cat ~/.app-store/auth/apple-developer-portal-domain.json on your device?

Contents of that file are

```
{
  "domain": "https://developer.apple.com"
}
```

> @BrandonMathis Can you try to do rm -rf ~/.app-store to clear the cache?

I deleted that file & was required to log back in so I beleive that did clear some cache but the issues persists

```
🐚 rm -rf ~/.app-store
🐚 eas submit --platform ios
★ eas-cli@9.0.8 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.


✔ What would you like to submit? › Select a build from EAS
✔ Which build would you like to submit? › - ID: 45d27a48-51b4-4234-8971-44c7c851d529 (21 hours ago)
Ensuring your app exists on App Store Connect. This step can be skipped by providing ascAppId in the submit profile. Learn
more: https://expo.fyi/asc-app-id

› Log in to your Apple Developer account to continue
✔ Apple ID: … xxxxxxx@xxxxxxxx.com
› Using password for xxxxxx@xxxxxxx.com from your local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
✔ Logged in, verify your Apple account to continue
Two-factor Authentication (6 digit code) is enabled for xxxxx@xxxxxxx.com. Learn more: https://support.apple.com/en-us/HT204915

✔ Please enter the 6 digit code you received at +1 (•••) •••-••00: … xxxxxx
✔ Valid code
✔ Logged in and verified
✔ Select a Team › XXXXXX XXXXXX Inc - Company/Organization (xxxxxxxx)
✔ Select a Provider › XXXXXXX XXXXXXX Inc (xxxxxx)
✔ Switched to provider: XXXXXXXXXX XXXXXXXXx Inc (xxxxxxx)

Cannot read properties of undefined (reading 'attributes')
Submission failed
    Error: submit command failed.
```
    
✅ This fixed the issue for me (updating my eas.json with some ios specific data)

> Updating my eas.json solved it for me! @brentvatne
> In the submit.production.ios section I added:
> 
> ascAppId
> appleId
> appleTeamId
>  "submit": { "production": { "ios": { "ascAppId": "", "appleId": "", "appleTeamId": "" } } }

Many thanks to the people in this issue & the Discord who help. I will close this issue now
