### ISSUE TITLE
EAS build does not recognize yarn 

### ISSUE THREAD

**Issue by zestsystem** [expo/eas-cli#2540]
### Build/Submit details page URL

https://expo.dev/accounts/utc/projects/utc-dance-mobile/builds/1ab25d6b-6528-4349-a536-a751d766021a

### Summary

The remote worker that does the builder cannot recognize local packages in a yarn workspace. When running `eas build --platform ios --local` I was able to get past the install stage. 

link to discord help forum: https://discord.com/channels/695411232856997968/1281090800851095644

### Managed or bare?

Managed

### Environment

`npx expo-env-info`
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /nix/store/6fjbdh80mh7c0cbzndd3zgzqvrhrc1ww-zsh-5.9/bin/zsh
    Binaries:
      Node: 20.14.0 - /etc/profiles/per-user/mikeyim/bin/node
      npm: 10.7.0 - /etc/profiles/per-user/mikeyim/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    Expo Workflow: managed

`npx expo-doctor`
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-picker/picker@2.8.0 - expected version: 2.7.5
  react-native-svg@15.6.0 - expected version: 15.2.0
  typescript@5.5.4 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

### Error output

We detected that 'apps/******' is a yarn workspace
Running "yarn install --no-immutable --inline-builds" in /Users/expo/workingdir/build directory
yarn install v1.22.21
warning Missing version in workspace at "/Users/expo/workingdir/build/apps/edge-worker", ignoring.
warning Missing name in workspace at "/Users/expo/workingdir/build/infra/cron", ignoring.
warning Missing name in workspace at "/Users/expo/workingdir/build/infra/eda", ignoring.
warning Missing name in workspace at "/Users/expo/workingdir/build/infra/elasticache", ignoring.
warning Missing name in workspace at "/Users/expo/workingdir/build/infra/marco", ignoring.
warning Missing version in workspace at "/Users/expo/workingdir/build/infra/redpanda", ignoring.
warning Missing name in workspace at "/Users/expo/workingdir/build/infra/vpc", ignoring.
[1/4] Resolving packages...
warning Resolution field "axios@0.26.1" is incompatible with requested version "axios@^1.6.0"
warning workspace-aggregator-b9d93ac6-7db6-41d5-8985-3a27a0745117 > @utc/cron > fastify-cron > @types/cron@2.4.0: This is a stub types definition. cron provides its own type definitions, so you do not need this installed.
warning Resolution field "axios@0.26.1" is incompatible with requested version "axios@^1.6.8"
warning workspace-aggregator-b9d93ac6-7db6-41d5-8985-3a27a0745117 > @utc/web > instantsearch.js > hogan.js > mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
error Couldn't find package "@utc/core@workspace:*" required by "@utc/cron@1.0.0" on the "npm" registry.
info Visit *****://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning workspace-aggregator-b9d93ac6-7db6-41d5-8985-3a27a0745117 > @utc/****** > react-native > @react-native/community-cli-plugin > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
Error: Couldn't find package "@utc/core-db@workspace:*" required by "@utc/cron@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core-db@workspace:*" required by "@utc/demo@0.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core-db@workspace:*" required by "@utc/marco@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core-db@workspace:*" required by "@utc/******@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core-db@workspace:*" required by "@utc/web@0.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core-db@workspace:*" required by "@utc/core@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core-db@workspace:*" required by "@utc/tournament-manager@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core-db@workspace:*" required by "@utc/integration@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core@workspace:*" required by "@utc/marco@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core@workspace:*" required by "@utc/******@1.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@utc/core@workspace:*" required by "@utc/web@0.0.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:36593:17)
    at Generator.throw (<anonymous>)
    at step (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Reproducible demo or steps to reproduce from a blank project

https://github.com/zestsystem/expo-yarn-monorepo-repro

**Comment by MauriceArikoglu** [comment]
Can confirm, this happens to us as well.

**Comment by colin-oos** [comment]
Happens to me also. Has anyone found a workaround to this?

**Comment by MauriceArikoglu** [comment]
> Happens to me also. Has anyone found a workaround to this?

@colin-oos we did, although not feasible for everyone.

First, configure eas to build locally.

Second, create a root tsconfig to share local files without requiring building https://github.com/vercel/turborepo/discussions/620#discussioncomment-4673458

In our case it's just types and utilities, so it works for us. It might not be suitable for every other case.
