### ISSUE TITLE
Authentication with Apple Developer Portal failed!

### ISSUE THREAD

**Issue by 22adubey** [expo/eas-cli#2726]
### Summary

Ran the eas build command but received this error after login in and verification step.  

### Managed or bare?

Bare

### Environment

expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.0 => 0.10.0 
      expo: ^50.0.13 => 50.0.20 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.12 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 13.4.1
      expo-cli: 6.3.10
    Expo Workflow: bare

### Error output

eas build --profile production --platform ios

✔ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.

This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them.

✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue

✔ Apple ID: … [email@email.com](mailto:email@email.com)

› Using password for [email@email.com](mailto:email@email.com) from your local Keychain

Learn more: https://docs.expo.dev/distribution/security#keychain

✔ Logged in, verify your Apple account to continue

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...

Authentication with Apple Developer Portal failed!

Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later

Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.0 => 0.10.0 
      expo: ^50.0.13 => 50.0.20 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.12 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 13.4.1
      expo-cli: 6.3.10
    Expo Workflow: bare

**Comment by szdziedzic** [comment]
It looks like https://github.com/expo/eas-cli/issues/2698, is it by any chance a duplicate?

**Comment by george-tux** [comment]
Also receiving this error on MacOS 15.1.1. Using eas-cli v13.4.2

**Comment by brandon-austin-lark** [comment]
I cant submit a build to app stores as well using the latest eas cli

**Comment by brandon-austin-lark** [comment]
`EXPO_NO_KEYCHAIN=1 EXPO_DEBUG=1 eas submit --platform ios`

```
Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
An unexpected error occurred. - An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/.'. Retrying after 3 seconds (remaining: 3)

✖ Failed to create App Store app PlaySpot
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
An unexpected error occurred. - An unexpected error occurred on the server side. If this issue continues, contact us at https://developer.apple.com/contact/.
Visit https://appstoreconnect.apple.com and resolve any warnings, then try again.
Submission failed
Error: Submission failed
    at IosSubmitCommand.resolveSubmissionOptionsAsync (/usr/local/lib/node_modules/eas-cli/build/submit/ios/IosSubmitCommand.js:58:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IosSubmitCommand.runAsync (/usr/local/lib/node_modules/eas-cli/build/submit/ios/IosSubmitCommand.js:39:25)
    at async attemptEvent (/usr/local/lib/node_modules/eas-cli/build/submit/submit.js:21:27)
    at async withAnalyticsAsync (/usr/local/lib/node_modules/eas-cli/build/analytics/common.js:7:24)
    at async submitAsync (/usr/local/lib/node_modules/eas-cli/build/submit/submit.js:17:12)
    at async Submit.runAsync (/usr/local/lib/node_modules/eas-cli/build/commands/submit.js:59:32)
    at async Submit.run (/usr/local/lib/node_modules/eas-cli/build/commandUtils/EasCommand.js:68:16)
    at async Submit._run (/usr/local/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/usr/local/lib/node_modules/eas-cli/node_modules/@oclif/core/lib/config/config.js:301:25)
    Error: submit command failed.
```

**Comment by 22adubey** [comment]
> It looks like #2698, is it by any chance a duplicate?

Yeah looks like its the same issue

**Comment by akratch** [comment]
I ran into the same exact issue the solution was deleting this folder: ~/.app-store/

And then re-running with EXPO_NO_KEYCHAIN=1

This triggered a re-login with my 2FA and then good to go. You can remove the folder with rm -r or by navigating to users/yourusername/ and then using CMD+SHIFT+. in order to view hidden files and delete.

**Comment by george-tux** [comment]
@akratch Yep that worked for me! Thanks!

**Comment by jameskennethrobinson** [comment]
Removing that folder did not work for me unfortunately

**Comment by brandon-austin-lark** [comment]
decided to build my project under a new name and id and it worked.

**Comment by 22adubey** [comment]
> I ran into the same exact issue the solution was deleting this folder: ~/.app-store/
> 
> And then re-running with EXPO_NO_KEYCHAIN=1
> 
> This triggered a re-login with my 2FA and then good to go. You can remove the folder with rm -r or by navigating to users/yourusername/ and then using CMD+SHIFT+. in order to view hidden files and delete.

This did not work for me

**Comment by george-tux** [comment]
Had it working but ran into this issue again when trying to submit. I don't know why but I got it working again after 

1. deleting ~/.app-store/ again
2. adding --auto-submit flag to the build command

so the final command i used that worked was `EXPO_NO_KEYCHAIN=1 eas build -p ios --profile production --auto-submit` 

after that i was prompted with 2fa again and was able to authenticate

**Comment by szdziedzic** [comment]
I try to test some changes to the headers we use for Apple auth, can you test if using my fork of CLI `npx -y @szdziedzic/eas-cli@latest` build helps with this issue?

**Comment by szdziedzic** [comment]
BTW I will close it so we can all track this issue in https://github.com/expo/eas-cli/issues/2698 so we don't have 2 separate conversations
