### ISSUE TITLE
Can't run local build due to credentials error

### ISSUE THREAD

**Issue by kbrandwijk** [expo/eas-cli#561]
When trying a local eas build, I get this error:
```
[PREPARE_CREDENTIALS] Preparing credentials
[PREPARE_CREDENTIALS] Creating keychain
[PREPARE_CREDENTIALS] 
Error: fastlane exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
    ...
    at Object.spawnAsync [as default] (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at Object.spawn [as default] (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/turtle-spawn/dist/index.js:17:42)
    at Object.runFastlane [as default] (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/fastlane/dist/index.js:10:40)
    at Keychain.create (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/credentials/keychain.js:27:33)
    at IosCredentialsManager.prepare (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/credentials/manager.js:50:29)
    at /Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/ios.js:25:45
    at BuildContext.runBuildPhase (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/context.js:57:34)
    at Object.iosBuilder (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/ios.js:24:39)
    at async Object.buildIosAsync (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/dist/ios.js:43:27)
    at async Object.buildAsync (/Users/kim/.nvm/versions/node/v12.22.1/lib/node_modules/eas-cli-local-build-plugin/dist/build.js:27:32)
[CLEAN_UP_CREDENTIALS] There is nothing to destroy, a keychain hasn't been created yet.
```

**Comment by dsokal** [comment]
Hi, 

Could you please share more details? 
- What's the **exact** command that you ran?
- What version of `fastlane` do you have?
- Could you try running the `fastlane run create_keychain ...` command on your own? See https://github.com/expo/eas-build/blob/main/packages/build-tools/src/ios/credentials/keychain.ts#L31 for how the `@expo/build-tools` is handling the keychain creation.

Thanks!

**Comment by dsokal** [comment]
I'm closing the issue because of the inactivity.
