### ISSUE TITLE
eas build "Cannot read property 'string' of undefined"

### ISSUE THREAD

**Issue by JustinDFuller** [expo/eas-cli#741]
### Summary

I just updated to `eas-cli` version `0.34.1`. Now, when I run `eas build` I get an error `Cannot read property 'string' of undefined`.

### Environment

```
> eas diagnostics

/home/justindanielfuller/code/purchaseplan.io/mobile/node_modules/cli-ux/lib/styled/table.js:285
        columns: command_1.flags.string({ exclusive: ['extended'], description: 'only show provided columns (comma-separated)' }),
                                 ^

TypeError: Cannot read property 'string' of undefined
    at /home/justindanielfuller/code/purchaseplan.io/mobile/node_modules/cli-ux/lib/styled/table.js:285:34
    at Object.<anonymous> (/home/justindanielfuller/code/purchaseplan.io/mobile/node_modules/cli-ux/lib/styled/table.js:314:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/justindanielfuller/code/purchaseplan.io/mobile/node_modules/cli-ux/lib/index.js:14:36)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
```

### Error output

```
> eas build --platform all --profile production

/home/justindanielfuller/code/purchaseplan.io/mobile/node_modules/cli-ux/lib/styled/table.js:285
        columns: command_1.flags.string({ exclusive: ['extended'], description: 'only show provided columns (comma-separated)' }),
                                 ^

TypeError: Cannot read property 'string' of undefined
    at /home/justindanielfuller/code/purchaseplan.io/mobile/node_modules/cli-ux/lib/styled/table.js:285:34
    at Object.<anonymous> (/home/justindanielfuller/code/purchaseplan.io/mobile/node_modules/cli-ux/lib/styled/table.js:314:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/justindanielfuller/code/purchaseplan.io/mobile/node_modules/cli-ux/lib/index.js:14:36)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
```

### Reproducible demo or steps to reproduce from a blank project

No runtime demo required.

**Comment by JustinDFuller** [comment]
I've tried installing many different versions of `eas-cli` and `cli-ux`. It did not help.

**Comment by JustinDFuller** [comment]
This appear after running `npm audi fix`. Reverting package-lock.json fixed the problem.
