### ISSUE TITLE
EAS build: TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by elebioda** [expo/eas-cli#742]
### Summary

Trying to build an IOS distro and when I provide my credentials I am getting this error output.

### Environment

  EAS CLI 0.34.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ~42.0.1 => 42.0.4
      expo-dev-client: ^0.6.3 => 0.6.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.14.13 => 0.14.13
    npmGlobalPackages:
      eas-cli: 0.34.1
      expo-cli: 4.12.12

### Error output

`✖ Logging in...
Authentication with Apple Developer Portal failed!
TypeError: Cannot read property 'trim' of undefined
    at /Users/Elebioda/.nvm/versions/node/v14.18.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:1031571
    at Array.map (<anonymous>)
    at new ServiceError (/Users/Elebioda/.nvm/versions/node/v14.18.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:1031562)
    at assertServiceErrors (/Users/Elebioda/.nvm/versions/node/v14.18.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:873724)
    at attemptLoginRequestAsync (/Users/Elebioda/.nvm/versions/node/v14.18.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:873289)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.loginWithUserCredentialsAsync (/Users/Elebioda/.nvm/versions/node/v14.18.1/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:871771)
    at async loginWithUserCredentialsAsync (/Users/Elebioda/.nvm/versions/node/v14.18.1/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:72:24)
    at async loginAsync (/Users/Elebioda/.nvm/versions/node/v14.18.1/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:44:16)
    at async authenticateAsync (/Users/Elebioda/.nvm/versions/node/v14.18.1/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:88:27)`

### Reproducible demo or steps to reproduce from a blank project

EAS_DEBUG=1 EAS_APP_STORE_DEBUG=1 EXPO_NO_KEYCHAIN=1 eas build -p ios --profile=development

**Comment by dsokal** [comment]
Hi @elebioda,
Could you please install `eas-cli@0.35.0` and let me know whether the issue went away?

**Comment by dsokal** [comment]
Closing because of the inactivity.
