### ISSUE TITLE
The following build commands failed: ▸ 	PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates

### ISSUE THREAD

**Issue by veeramarni** [expo/eas-cli#773]
### Summary

I could not find the reason why the build is failing, i don't have exp-updates in the package.json but still something causing this issue. 

### Environment

eas build --profile preview -p ios --clear-cache

### Error output

```
› Compiling expo-image-picker Pods/EXImagePicker » EXImagePicker-dummy.m
› Executing expo-file-system Pods/EXFileSystem » [CP] Copy XCFrameworks
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/AdminideStack-gviqdtaelgnjllgiejbjzrtycmki/Build/Intermediates.noindex/ArchiveIntermediates/AdminideStack/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-49F93F43B9AB98D31CB55A39585BC5D3.sh (in target 'EXUpdates' from project 'Pods')
▸ (1 failure)
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/AdminideStack-gviqdtaelgnjllgiejbjzrtycmki/Build/Intermediates.noindex/ArchiveIntermediates/AdminideStack/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-49F93F43B9AB98D31CB55A39585BC5D3.sh (in target 'EXUpdates' from project 'Pods')
(1 failure)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.185.1                 |
| sdk         | iPhoneOS15.0.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[stderr] [!] Error building the application - see the log above
Error: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
```

### Reproducible demo or steps to reproduce from a blank project

Repo: https://github.com/cdmbase/fullstack-pro

Commands to run install

 `yarn && yarn build` and `npm i -g lerna`

to start the mobile build
`lerna exec --scope='*mobile' yarn build:eas`

**Comment by brentvatne** [comment]
hi there! please refer to https://docs.expo.dev/build-reference/troubleshooting/

you likely need to refer to your full xcode logs to see the full error (they are at the bottom of the build page)

**Comment by veeramarni** [comment]
@brentvatne thanks for the link, I was able to debug and find the issue. It is related to code [here](https://github.com/expo/expo/blob/954da7b81871694df2f2d4cac43cd51f653b3e4e/packages/expo-updates/scripts/createManifest.js#L80)



```
    /bin/sh -c /Users/expo/Library/Developer/Xcode/DerivedData/FullStackPro-emqjdebtjuikosessatmdomuqpcv/Build/Intermediates.noindex/ArchiveIntermediates/FullStackPro/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-49F93F43B9AB98D31CB55A39585BC5D3.sh
TypeError [ERR_INVALID_ARG_TYPE]: The "directory" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at process.wrappedChdir (internal/bootstrap/switches/does_own_process_state.js:115:3)
    at process.chdir (/Users/expo/workingdir/build/node_modules/graceful-fs/polyfills.js:22:11)
    at /Users/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:23:11
    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:81:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by kav** [comment]
See https://github.com/expo/expo/issues/15325
