### ISSUE TITLE
EAS Local build fails (on Windows)

### ISSUE THREAD

**Issue by pepyta** [expo/eas-cli#778]
### Summary

When I run `eas build --platform android --local` on a fresh Managed workflow, it throws an `invalidTagName` error.

### Environment

  EAS CLI 0.37.0 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.33.0.
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1

### Error output

```
Error: Cannot find module 'expo-dev-client/package.json'
Require stack:
- C:\Users\pepyta\projectName\mobile\noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at resolveFileName (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\node_modules\resolve-from\index.js:43:9)
    at module.exports (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\node_modules\resolve-from\index.js:46:47)
    at isExpoDevClientInstalledAsync (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\build\build\utils\devClient.js:68:36)
    at ensureExpoDevClientInstalledForDevClientBuildsAsync (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\build\build\utils\devClient.js:18:15)
    at Build.runAsync (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\build\commands\build\index.js:62:83)
    at async Build._run (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\node_modules\@oclif\command\lib\command.js:43:20)
    at async Config.runCommand (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\pepyta\AppData\Roaming\npm\node_modules\eas-cli\node_modules\@oclif\command\lib\main.js:27:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\pepyta\\projectName\\mobile\\noop.js' ]
}
- Linking to project @pepyta/mobile
✔ Linked to project @pepyta/mobile (​https://expo.dev/accounts/pepyta/projects/mobile​)
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials tjUPGKeZru (default)
- Compressing project files
C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:296
      throw invalidTagName(spec)
      ^

Error: Invalid tag name "eyJqb2I...Hl0YSJ9fQ==": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:91:15)
    at fromRegistry (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:296:13)
    at resolve (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:81:12)
    at npa (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:52:10)
    at Function.parseArgs (C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\parse-args.js:48:23)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npx-cli.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'EINVALIDTAGNAME'
}
    Error: npx exited with non-zero code: 1
- Compressing project files
```

Please note that I truncated the base64 string because it contains sensitive information. 

### Reproducible demo or steps to reproduce from a blank project

1. Create a new blank project (I created a Managed workflow with a blank typescript template)
2. Run `eas build --platform android --local`. (Without the --local switch, it works fine)
3. Profit!

**Comment by wkozyra95** [comment]
I can confirm it's a bug, it's happening if someone is using npm 6 or lower (it works with npm 7). We use command
`npx -y eas-cli-local-build-plugin:version base64jobobject` to run build locally, but the `-y` option is not available in older version of npm/npx

We will fix that soon, but I'm afraid it won't help you much, local builds are supported only on Linux and macos(it should also work under WSL, but we don't test it on that platform). Normally proper info would be displayed in the terminal, but this bug is happening before we check the platform.

**Comment by pepyta** [comment]
I can confirm, that npm version 7 works just fine.
Also, I was able to run the build command on WSL just fine.

 Thank you for your help!

**Comment by liveakshay** [comment]
Any updates on this?  This is still happening in Oct 2024!
