### ISSUE TITLE
[iOS Build] Failing with workspace error

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/eas-cli#874]
### Build/Submit details page URL

https://expo.dev/accounts/lightstalker89/projects/dec112-react-native/builds/9293311d-563a-4206-8e65-76c89f10e899

### Summary

I'm trying to build the iOS app via EAS CLI, but I'm no getting the following errors.
I did not change anything or upgrade any dependencies and I'm using the latest SKD (v44)

I also tried to start the build with --clear-cache and also disabled caching but this did not help.
Same error if I try to build it locally.

### Managed or bare?

Managed

### Environment

 EAS CLI 0.42.4 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/opt/nvm/versions/node/v14.17.5/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.3.0 - /usr/local/opt/nvm/versions/node/v14.17.5/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ~44.0.0 => 44.0.0 
      expo-cli: ^5.0.3 => 5.0.4 
      expo-dev-client: ~0.7.2 => 0.7.2 
      expo-updates: ~0.11.3 => 0.11.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.3
    Project workflow: managed

### Error output

`[!] Please close any current Xcode sessions and use dec112reactnative.xcworkspace for this project from now on.
102
[!] An error occurred while processing the post-integrate hook of the Podfile.
103
104
undefined method expo_patch_react_imports!' for #<Pod::Podfile:0x00007feae2c934a0>`

### Reproducible demo or steps to reproduce from a blank project

No idea on how to give you a reproducible example!?

**Comment by Livijn** [comment]
I have the same issue, happened when I updated expo. Seen several people having the same issue at Discord.

**Comment by mariomurrent-softwaresolutions** [comment]
I just heard that there is a new expo version (44.0.1). Maybe the issue is fixed there.
I'll try it out tomorrow

**Comment by acrdlph** [comment]
I am also facing this issue and here is a minimal reproducible example: https://github.com/acrdlph/eas-mcve

**Comment by enesozturk** [comment]
Having the same issue. 
<details>
<summary> Stack trace 👇🏽 </summary>

```bash
Installing pods
Using Expo modules
Auto-linking React Native modules for target `build`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNReanimated, RNSVG, RNScreens, expo-dev-client, expo-dev-launcher, expo-dev-menu, expo-dev-menu-interface, react-native-netinfo, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.2
CocoaPods 1.11.2 is available.
To update use: `sudo gem install cocoapods`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing EXApplication (4.0.1)
Installing EXConstants (13.0.0)
Installing EXErrorRecovery (3.0.4)
Installing EXFileSystem (13.1.0)
Installing EXFont (10.0.4)
Installing EXJSONUtils (0.2.0)
Installing EXKeepAwake (10.0.1)
Installing EXManifests (0.2.2)
Installing EXSplashScreen (0.14.1)
Installing EXUpdatesInterface (0.5.0)
Installing EXWebBrowser (10.1.0)
Installing Expo (44.0.0)
Installing ExpoLocalization (12.0.0)
Installing ExpoModulesCore (0.6.3)
Installing FBLazyVector (0.64.3)
Installing FBReactNativeSpec (0.64.3)
Installing RCT-Folly (2020.01.13.00)
Installing RCTRequired (0.64.3)
Installing RCTTypeSafety (0.64.3)
Installing RNCAsyncStorage (1.15.13)
Installing RNCMaskedView (0.2.6)
Installing RNGestureHandler (2.1.0)
Installing RNReanimated (2.3.1)
Installing RNSVG (12.1.1)
Installing RNScreens (3.10.1)
Installing React (0.64.3)
Installing React-Core (0.64.3)
Installing React-CoreModules (0.64.3)
Installing React-RCTActionSheet (0.64.3)
Installing React-RCTAnimation (0.64.3)
Installing React-RCTBlob (0.64.3)
Installing React-RCTImage (0.64.3)
Installing React-RCTLinking (0.64.3)
Installing React-RCTNetwork (0.64.3)
Installing React-RCTSettings (0.64.3)
Installing React-RCTText (0.64.3)
Installing React-RCTVibration (0.64.3)
Installing React-callinvoker (0.64.3)
Installing React-cxxreact (0.64.3)
Installing React-jsi (0.64.3)
Installing React-jsiexecutor (0.64.3)
Installing React-jsinspector (0.64.3)
Installing React-perflogger (0.64.3)
Installing React-runtimeexecutor (0.64.3)
Installing ReactCommon (0.64.3)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing expo-dev-client (0.7.2)
Installing expo-dev-launcher (0.9.1)
Installing expo-dev-menu (0.8.6)
Installing expo-dev-menu-interface (0.4.2)
Installing glog (0.3.5)
Installing react-native-netinfo (7.1.3)
Installing react-native-safe-area-context (3.3.2)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `build.xcworkspace` for this project from now on.
[!] An error occurred while processing the post-integrate hook of the Podfile.

undefined method `expo_patch_react_imports!' for #<Pod::Podfile:0x00007ff157a0b478>
/Users/expo/workingdir/build/ios/Podfile:44:in `block (3 levels) in from_ruby'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:196:in `post_integrate!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:925:in `run_podfile_post_integrate_hook'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:913:in `block in run_podfile_post_integrate_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:912:in `run_podfile_post_integrate_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:841:in `block in integrate_user_project'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:836:in `integrate_user_project'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:180:in `integrate'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `<main>'
[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `AB152023C24E4497B47C638F` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod exited with non-zero code: 1
```
</details>

Versions: 
```json
"expo": "^44.0.0",
"eas-cli": eas-cli/0.42.4 darwin-x64 node-v14.18.1
```

What I did until the last successful build:
- Moved my app to my personal profile to my organization by setting `expo` config under the `app.config.js`.
- Adding expo-splash-screen package

**Comment by jesuscovam** [comment]
I fixed this for my project with

`npm i expo@44.0.1`

**Comment by enesozturk** [comment]
`expo@44.0.1`also worked for me, thanks.

**Comment by kendallroth** [comment]
Was running into the same issue, with the only changes to `package.json` since the last successful build (3 days ago) being a patch bump to `expo-splash-screen@~0.14.1` and adding `expo-application@~4.0.1`. After checking out a previous commit, I was able to build successfully. I also tried to upgrade `expo@44.0.1` and can confirm that this works.

**Comment by mariomurrent-softwaresolutions** [comment]
Upgrading to 44.0.1 seems to solve the issue
