### ISSUE TITLE
[eas build] There is neither a value or a policy set for the runtime version on "ios"

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/eas-cli#895]
### Build/Submit details page URL

https://expo.dev/accounts/garrettg/builds/a79ed52f-1945-4f1b-88f1-42b846c1c9e2

### Summary

Running `eas build --platform ios --profile development` shows `There is neither a value or a policy set for the runtime version on "ios"`. However, when modifying `app.config.ts`, the `runtimeVersion` is optional, and has a scary warning (Expo 44):
```ts
    /**
     * **Note: Don't use this property unless you are sure what you're doing**
     *
     * The runtime version associated with this manifest for the iOS platform. If provided, this will override the top level runtimeVersion key.
     * Set this to `{"policy": "nativeVersion"}` to generate it automatically.
     */
    runtimeVersion?: string | {
        policy: 'nativeVersion' | 'sdkVersion';
    };
```

### Managed or bare?

bare

### Environment

  EAS CLI 0.43.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.22.7 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ^44.0.0 => 44.0.4
      react-native: 0.64.3 => 0.64.3
    Project workflow: generic

### Error output

```
Error: There is neither a value or a policy set for the runtime version on "ios"
    at Object.getRuntimeVersion (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/node_modules/@expo/config-plugins/build/utils/Updates.js:163:11)
    at getRuntimeVersionNullable (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/build/build/metadata.js:22:41)
    at collectMetadataAsync (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/build/build/metadata.js:42:31)
    at async prepareBuildRequestForPlatformAsync (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/build/build/build.js:53:22)
    at async prepareIosBuildAsync (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/build/build/ios/build.js:45:12)
    at async startBuildAsync (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/build/build/runBuildAndSubmit.js:144:33)
    at async prepareAndStartBuildAsync (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/build/build/runBuildAndSubmit.js:132:19)
    at async runBuildAndSubmitAsync (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/build/build/runBuildAndSubmit.js:49:49)
    at async Build.runAsync (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/build/commands/build/index.js:30:9)
    at async Build._run (/Users/gsquare567/.config/yarn/global/node_modules/eas-cli/node_modules/@oclif/core/lib/command.js:52:22)
```

### Reproducible demo or steps to reproduce from a blank project

1. Create Expo project without `runtimeVersion` set in `app.config.ts`
2. Run `eas build --platform ios --profile development`

**Comment by dsokal** [comment]
@garrett-gottlieb
Could you please provide a reproducible demo of this issue? Ideally, a Github repository and exact repro steps.

**Comment by sreuter** [comment]
@garrett-gottlieb Running into the same issue here. Did you figure this out yet by any chance?
