### ISSUE TITLE
HTTPError: Response code 400 (Bad Request)

### ISSUE THREAD

**Issue by vdiorio** [expo/eas-cli#958]
### Summary

Everytime I try to run `eas build` i get the following console log:
```
✔ Select platform › All
✔ Linked to project @vdiorio/EdhCounter (​https://expo.dev/accounts/vdiorio/projects/EdhCounter​)

🤖 Android build
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials SEw7oKGFUv (default)
✖ Uploading to EAS Build (65.6 KB / 1.4 MB)
    HTTPError: Response code 400 (Bad Request)
```

### Managed or bare?

Managed

### Environment

  EAS CLI 0.46.0 environment info:
    System:
      OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Utilities:
      Git: 2.25.1 - /usr/bin/git
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.0.3
    Project workflow: managed

### Reproducible demo or steps to reproduce from a blank project

just run eas build at any moment

**Comment by wkozyra95** [comment]
can you run `DEBUG=* eas build` and provide the output

uploading project is a direct upload to aws s3 with presigned URL, after upload starts it does not interact with expo servers. Is there anything on your system that might block requests to aws? have you tried running build on different machine preferably on CI?

**Comment by vdiorio** [comment]
Response of `DEBUG=* eas build`
```
  config reading core plugin /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli +0ms
  config loadJSON /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/package.json +0ms
  config loadJSON /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/oclif.manifest.json +0ms
  config:eas-cli using manifest from /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/oclif.manifest.json +0ms
  config reading user plugins pjson /home/vdiorio/.local/share/eas-cli/package.json +0ms
  config loadJSON /home/vdiorio/.local/share/eas-cli/package.json +0ms
  config loading plugins [
  '@oclif/plugin-autocomplete',
  '@oclif/plugin-help',
  '@expo/plugin-warn-if-update-available'
] +0ms
  config reading core plugin /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete +0ms
  config loadJSON /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/package.json +0ms
  config reading core plugin /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-help +0ms
  config loadJSON /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-help/package.json +0ms
  config reading core plugin /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available +0ms
  config loadJSON /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/package.json +0ms
  config loadJSON /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  config loadJSON /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config loadJSON /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config:@oclif/plugin-autocomplete using manifest from /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-autocomplete/oclif.manifest.json +0ms
  config:@oclif/plugin-help using manifest from /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  config:@expo/plugin-warn-if-update-available using manifest from /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/oclif.manifest.json +0ms
  config config done +6ms
  config start init hook +0ms
  eas:@expo/plugin-warn-if-update-available:hooks:init start (require) /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/@expo/plugin-warn-if-update-available/lib/hooks/init/check-update.js +0ms
  eas:@expo/plugin-warn-if-update-available:hooks:init done +3ms
  config init hook done +36ms
  config runCommand build [] +1ms
  config:eas-cli (require) /home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/build/commands/build +828ms
  config start prerun hook +775ms
  config prerun hook done +0ms
  eas:build init version: @oclif/core@1.1.2 argv: [] +0ms
✔ Select platform › Android
✔ Linked to project @vdiorio/EdhCounter (​https://expo.dev/accounts/vdiorio/projects/EdhCounter​)
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials SEw7oKGFUv (default)
✖ Uploading to EAS Build (65.6 KB / 1.3 MB)
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/home/vdiorio/.nvm/versions/node/v14.19.0/lib/node_modules/eas-cli/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
I have disabled firewalls and everything i could find that could be causing the problem, I'll try another machine soon.

**Comment by wkozyra95** [comment]
Tested on your exact version of node in docker by running
```
docker run -it --entrypoint bash node:14.19.0
$ npm -g i expo-cli eas-cli
$ mkdir test && cd test
$ expo init
$ EXPO_TOKEN=mytoken eas build // you can just loging
```
If you have a docker setup try the above steps, if it fails in docker it's some networking issue on your system or maybe your ISP is blocking it for some reason(might be worth trying VPN), if it works in odcker try reinstalling nvm

**Comment by vdiorio** [comment]
Thank you a lot, vpn solved my problem. No idea how to solve my ISP issue, but now I can work again
