### ISSUE TITLE
Something changed in EAS build android infrastructure between Feb 16th and 18th ?

### ISSUE THREAD

**Issue by dcassou** [expo/eas-cli#982]
### Build/Submit details page URL

https://expo.dev/accounts/starlingpartners/projects/daenscout/builds/09c292b9-64a3-4f17-b09c-960c2c4cc38f

### Summary

EAS build for android target is not working anymore, Gradle complaining on non escaped characters is app name (iOS is still fine). The same commit was working perfectly three days before.
faulty build is :  [faulty](https://expo.dev/accounts/starlingpartners/projects/daenscout/builds/09c292b9-64a3-4f17-b09c-960c2c4cc38f)
working build is : [working](https://expo.dev/accounts/starlingpartners/projects/daenscout/builds/ee4ec731-aba6-4b37-b4f6-c237b4f5305e) 
I may have upgraded eas/expo CLI between the two builds but I have made so many tests to debug this issue that I do not remember when I have made the upgrade.

### Managed or bare?

managed

### Environment

```
  EAS CLI 0.47.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.28.0. - /cmd/git
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      expo-dev-client: ~0.8.4 => 0.8.4
      expo-updates: ~0.11.6 => 0.11.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Project workflow: managed
```

### Error output

eas CLI output 
```
eas build -p android --profile live
- Linking to project @company/slug
✔ Linked to project @company/slug (​https://expo.dev/accounts/company/projects/slug​)

Expo Metro config:
- Bundler target: bare
- Legacy: false
- Extensions: ts, tsx, js, jsx, json
- React Native: xxx\src\node_modules\react-native
- Babel config: xxx\src\babel.config.js
- Resolver Fields: react-native, browser, main
- Exotic: false

✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials upy-rfYEcP (default)
- Compressing project files
- Uploading to EAS Build (0 / 7.1 MB)
✔ Uploaded to EAS 3s Learn more: https://expo.fyi/eas-build-archive
Error: There is neither a value or a policy set for the runtime version on "android"
    at Object.getRuntimeVersion (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\node_modules\@expo\config-plugins\build\utils\Updates.js:163:11)
    at getRuntimeVersionNullable (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\build\build\metadata.js:21:41)    at collectMetadataAsync (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\build\build\metadata.js:41:31)     
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async prepareBuildRequestForPlatformAsync (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\build\build\build.js:51:22)
    at async prepareAndroidBuildAsync (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\build\build\android\build.js:47:12)
    at async startBuildAsync (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\build\build\runBuildAndSubmit.js:147:33)
    at async prepareAndStartBuildAsync (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\build\build\runBuildAndSubmit.js:138:19)
    at async runBuildAndSubmitAsync (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\build\build\runBuildAndSubmit.js:53:49)
    at async Build.runAsync (xxx\Roaming\nvm\v16.13.2\node_modules\eas-cli\build\commands\build\index.js:31:9)Starting Android build

Build details: https://expo.dev/accounts/company/builds/4902d8b6-e650-4883-98bb-5d84c2bf9975

Waiting for build to complete. You can press Ctrl+C to exit.
```

Gradle output
```
> Task :unimodules-task-manager-interface:packageReleaseResources
> Task :app:mergeReleaseResources FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:mergeReleaseResources'.
[stderr] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]    > Android resource compilation failed
[stderr] /home/expo/workingdir/build/android/app/src/main/res/values/strings.xml:2:3-59: AAPT: error: unescaped apostrophe in string
[stderr]          
[stderr]      /home/expo/workingdir/build/android/app/src/main/res/values/strings.xml:2:3-59: AAPT: error: not a valid string.
[stderr]          
[stderr]      /home/expo/workingdir/build/android/app/build/intermediates/incremental/mergeReleaseResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.
[stderr]          
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 5m 23s
```

### Reproducible demo or steps to reproduce from a blank project

Have not been able to reproduce the bug from a blank project.
Same basic config, i.e. blank project custom app.config.js and custom env declared in eas.json builds fine

app.config.js
```
export default ({ config }) => {
  return { ...config, name: process.env.EXPO_NAME };
};
```
eas.json
```
{
	"cli": {
		"version": ">= 0.47.0"
	},
	"build": {
		"development": {
			"developmentClient": true,
			"distribution": "internal"
		},
		"preview": {
			"distribution": "internal"
		},
		"production": {
			"env": {
				"EXPO_NAME": "Observ'acteurs"
			}
		}
	},
	"submit": {
		"production": {}
	}
}
```

**Comment by wkozyra95** [comment]
hi, there was a small change that affected different fields in `values/strings.xml`, I'll take a look and try to reproduce that.

**Comment by dcassou** [comment]
one more input : `eas build --local` is building fine

**Comment by wkozyra95** [comment]
sorry forgot the message here yesterday, it should be fixed
local works before previous changes were not deployed yet

**Comment by dcassou** [comment]
it's working. Thanks !
